### ISSUE TITLE
Custom certificate lifetime

### ISSUE THREAD

**Issue by jurajsucik** [shibayan/keyvault-acmebot#101]
Would be great if you could add an option for a user to define a certificate lifetime instead of using the default 90 days. It would allow acmebot to issue even shorter lived certificates. 

I see several scenarios where this could useful:
- testing 
- improved security by using short lived certificates 
- some CA allow to use ACME protocol with lifetime that is higher than 90 days - applicable only if you decide to support other ACME compatible CA :)

**Comment by shibayan** [comment]
I have decided not to implement to this proposal.

- Better to use Staging ACME Endpoint for testing
- There is little to be gained by making it shorter than 90 days
- Implemented Web UI for explicitly updating
