### ISSUE TITLE
Multiple Subscriptions

### ISSUE THREAD

**Issue by xelencin** [shibayan/keyvault-acmebot#103]
It appears by default that key vault acmebot is scoped to the subscription is is deployed in, is it possible to use a single instance with multiple subscriptions or is an instance required per subscription?

**Comment by shibayan** [comment]
Internally, it is possible to support subscriptions that are associated with the same AAD tenant, but it is limited to one subscription because it may confuse users.

I would like to consider if there are many requests.

**Comment by xelencin** [comment]
Great thanks. Our use case is that we are essentially a holdings company that has multiple business entities, and in addition to this each entity has both a devtest and production subscription. As-is this is requiring us to deploy several instances of key vault acmebot but ideally we would run a single instance in a "shared services" subscription.

**Comment by andyzib** [comment]
I'll second this. Currently our DNS zones are in a different subscription from where we want to deploy Azure Application Gateway(s) and keyvault-acmebot. Thanks for taking this feature under consideration.

**Comment by Crossbow78** [comment]
@andyzib 
The application configuration has a 'Acmebot:SubscriptionId' setting that should point at the subscription with your DNS Zones. You can still deploy your Azure Function in any other (unnamed) subscription, that doesn't matter.

**Comment by shibayan** [comment]
When implementing the DNS provider model, I’m considering specifying multiple subscription IDs.

It's not high priority, but I will implement it eventually.

**Comment by shibayan** [comment]
After reviewing it, I decided not to implement it because there is not much to gain for the complexity.

**Comment by wonsil** [comment]
Basically install it once for each subscription and update each subscription as new versions come out?
