### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by soderlind** [shibayan/keyvault-acmebot#110]
**Describe the solution you'd like**
Instead of using the Web UI, I'd like to have an REST API I can use to add domains.

**Describe alternatives you've considered**
As far as I know, there's no API alternative. If it is, please tell me, and close the ticket.

**Comment by shibayan** [comment]
You can call the `api/add-certificate` API with the following parameters.

POST /api/add-certificate
```json
{
  "Domains": [ "contoso.com", "www.contoso.com" ]
}
```

When calling the API externally, turn off App Service Authentication and use the Function's Host Key to authenticate.

**Comment by shibayan** [comment]
Docs https://github.com/shibayan/keyvault-acmebot/wiki/REST-API

**Comment by soderlind** [comment]
Thank you @shibayan

**Comment by scastellanosnqn** [comment]
> You can call the `api/add-certificate` API with the following parameters.
> 
> POST /api/add-certificate
> 
> ```json
> {
>   "Domains": [ "contoso.com", "www.contoso.com" ]
> }
> ```
> 
> When calling the API externally, turn off App Service Authentication and use the Function's Host Key to authenticate.

Hi shibayan, is not posible to use the dashboard and the REST API at the same time ? Or use the REST API without disabling de App Service Authentication ?
