### ISSUE TITLE
Question: Zone apex domain

### ISSUE THREAD

**Issue by soderlind** [shibayan/keyvault-acmebot#111]
Using the Web UI, how do I add a certificate for a [zone apex domain](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-how-to-onboard-apex-domain#create-an-alias-record-for-zone-apex)? 

From the Web UI screenshot I understand that I can add a certificate for `sub1.contoso.com`, but how do I do it for `contoso.com` (if `contoso.com` is zone apex domain) ?

**Comment by shibayan** [comment]
You can issue a certificate for Zone Apex by adding an empty record name.

**Comment by soderlind** [comment]
Thank you @shibayan :)
