### ISSUE TITLE
Certificate is not updated

### ISSUE THREAD

**Issue by rzal** [shibayan/keyvault-acmebot#113]
None of the certificates have been update after they entered within 30 days of their expiry date.

I looked for traces and exceptions in the Application Insight tool for the last 3 days, but couldn't find anything relevant. I also went to `RenewCertificates_Timer` and manually triggered it, but no luck.

Could you help me to troubleshoot this?

![image](https://user-images.githubusercontent.com/26010553/82881739-99c00900-9f2f-11ea-989e-
1367ff13e092.png)

**Comment by shibayan** [comment]
Due to a bug in Azure Functions Runtime 3.0.13614, the application temporarily stopped working properly.

Now that the fix is complete on the application side, restart the Function App and rerun `RenewCertificates_Timer` from the Azure Portal, or wait for the timer to work.

**Comment by rzal** [comment]
Hi 達郎, I noticed the certs were refreshed a few minutes after my OP. Many thanks for your swift action! Rob
