### ISSUE TITLE
Orchestrator function 'IssueCertificate' failed Cannot deserialize the current JSON array

### ISSUE THREAD

**Issue by skulawik** [shibayan/keyvault-acmebot#123]
After having the issue with the appservice-acmebot i have installed the keyvault version additionally. After configuring it i was able to see all my DNS and selected one of the entries and entered a random domain name "test23234.xiona.de"  clicking on submit on add-certificate the following error occures:

`Orchestrator function 'IssueCertificate' failed: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.ValueTuple`2[Microsoft.Azure.Management.WebSites.Models.Site,System.String[]]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.`

**Comment by shibayan** [comment]
Key Vault version does not use `Microsoft.Azure.Management.WebSites`, there is no reason for this error.
You haven't deployed new Azure Functions, have you? I cannot advise against irregular operations.

**Comment by skulawik** [comment]
@shibayan The keyvault acmebot has been deployed completely new by using the https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fshibayan%2Fkeyvault-acmebot%2Fmaster%2Fazuredeploy.json 
but beside the existing appservice-acmebot.
Both are running seperately. Interestingly this is also an error that occured "sometimes" - after several tries and no changes in Azure at all it went through it. Question is, how is the orchestration function working in the Function App - may it randomly call the other function app because the functions in the function app are with the same name? 
I dont see any irregular operations in what i did here.

**Comment by shibayan** [comment]
You are probably using the same Storage Account. Deploy to a different resource group.
