### ISSUE TITLE
DNS Zone Dropdown sometimes is empty

### ISSUE THREAD

**Issue by skulawik** [shibayan/keyvault-acmebot#124]
When reloading the page, loading the DNS Zones Dropdown takes minutes and is sometimes empty. Pressing reload again then sometimes loads the list, sometimes it still keeps empty.

![Bildschirmfoto 2020-06-10 um 10 03 06](https://user-images.githubusercontent.com/367678/84242966-d714c100-ab01-11ea-95b2-09e29bd9ef76.jpg)

**Comment by shibayan** [comment]
This is a cache problem on the RBAC side of Azure.

**Comment by skulawik** [comment]
ok - so we cant do anything about it?

**Comment by shibayan** [comment]
If the RBAC is not working for a few hours even though it is configured correctly, create the Support Request to Microsoft.
