### ISSUE TITLE
Add root domain to SAN for wildcard certificate requests

### ISSUE THREAD

**Issue by raphael-liming** [shibayan/keyvault-acmebot#127]
**Is your feature request related to a problem? Please describe.**
Wildcard certificate requests don't include the root domain as a SAN on the wildcard certificate request.

**Describe the solution you'd like**
Add the root domain to the request.

**Comment by shibayan** [comment]
Rather than automatically adding root when adding a wildcard domain, I address this issue by adding a message to the web UI.

**Comment by raphael-liming** [comment]
I'm currently calling it as an API (disabled auth). How should I construct the request so that a wildcard certificate includes the SAN in that case?

**Comment by shibayan** [comment]
it's simple. Please include the root domain in your request and see the Wiki for API specifications.
