### ISSUE TITLE
Naming conventions used by the deployment script

### ISSUE THREAD

**Issue by justSteve** [shibayan/keyvault-acmebot#135]
**Is your feature request related to a problem? Please describe.**
I've used your **_'Deploy to Azure'_** button and let the script create all resources from scratch. That's resulted in a number of duplicated resource names being generated.

**Describe the solution you'd like**
I believe the script would be more useful if discrete names were assigned to each of the resources so that the type of resource could be inferred based on a string found within the name. 

E.G. Using the existing script I specified that the Function App should be named _'letsencrypt-app'_ which resulted in _'letsencrypt-app-x5uf'_ being used for App Insights, Key vault, App Service plan, as well as the function app itself.

First off I'm surprised Azure is permitting that - many times it flags dupped names as invalid.

**Describe alternatives you've considered**
I think we'd be better served if the results were something along the lines of:

- letsencrypt-ai
- letsencrypt-kv
- letsencrypt-plan

**Additional context**
I supposed i could have a go at updating the script and submitted a PR but first off wonder if there's specific logic behind the current choices that I haven't considered.

none-the-less....thanks much for the effort put into the project

**Comment by shibayan** [comment]
Thanks for the feedback, I will be improving our resources to follow Azure's recommended naming conventions.

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging
