### ISSUE TITLE
Experience Http Error 403 when accessing https://YOUR-FUNCTIONS.azurewebsites.net/add-certificate

### ISSUE THREAD

**Issue by swiftoffice2018** [shibayan/keyvault-acmebot#140]
I use the same template as last night. I did a redeployment and this error happen. How can I print out the logs?

**Comment by shibayan** [comment]
Enable App Service Authentication
https://github.com/shibayan/keyvault-acmebot#3-enable-app-service-authentication

**Comment by voyager163** [comment]
I did switch on the app service authentication.

**Comment by swiftoffice2018** [comment]
Sorry, I found the configuration error.

**Comment by voyager163** [comment]
Hi Shibayan, 

Thanks for the pointing me the correct direction. I found that i forget to set one of the settings.
