### ISSUE TITLE
Key Vault Certificate Renew?

### ISSUE THREAD

**Issue by voyager163** [shibayan/keyvault-acmebot#145]
Will the issued certificate that is downloaded from Key Vault and use within azure be automatically renewed 30 days before their expiration?

In addition, can i check if one subscription user assigned managed identity can assess another subscription key vault certificate? I having issue setup HTTPS within the Application Gateway without downloading and uploading certificate. I cannot find the key vault.

Sorry to ask stupid question.

![WhatsApp Image 2020-08-14 at 16 35 19](https://user-images.githubusercontent.com/4599055/90231302-8e54ed80-de4d-11ea-9d0f-15bd5dd11a6f.jpeg)

**Comment by shibayan** [comment]
>Will the issued certificate that is downloaded from Key Vault and use within azure be automatically renewed 30 days before their expiration?

Yes. However, it's not exactly 30 days ago, but rather the day of the week when the Timer runs, so it's a little back and forth. Specifically, it runs on Mondays, Wednesdays and Fridays.

>In addition, can i check if one subscription user assigned managed identity can assess another subscription key vault certificate? I having issue setup HTTPS within the Application Gateway without downloading and uploading certificate. I cannot find the key vault.

To use a Key Vault certificate on Application Gateway, you must create a User-assigned Managed Identity, configure a Key Vault access policy and enable the Key Vault soft-delete feature.

https://docs.microsoft.com/en-us/azure/application-gateway/configure-keyvault-ps

**Comment by voyager163** [comment]
Hi Shibayan,

I tried this before to create a user assigned Managed identity, but it do not seems to be able to read the key vault stored in another subscription even through i configured a key value access policy. If everything is in the same resource group, the managed identity can access it. Do you happen to know why?

"To use a Key Vault certificate on Application Gateway, you must create a User-assigned Managed Identity, configure a Key Vault access policy and enable the Key Vault soft-delete feature."

**Comment by shibayan** [comment]
This is not related to Key Vault Acmebot, so it's closed. I recommend that you contact Azure support.
