### ISSUE TITLE
Certificate is Expired by One Day at Creation

### ISSUE THREAD

**Issue by hhschreib** [shibayan/keyvault-acmebot#151]
Hello!  Your Acmebot Function App worked great.  I just wanted to confirm Will the certificates auto-refresh when approaching expiration date?  Appreciate your perspectives and thanks for the great Azure Function App!

Regards,

Herb

![exp](https://user-images.githubusercontent.com/62551054/92312451-a7554800-ef8e-11ea-8a0b-5cf1e5c00483.PNG)

**Comment by shibayan** [comment]
Yes, It is automatically updated about 30 days ago.
https://github.com/shibayan/keyvault-acmebot#renew-an-existing-certificate
