### ISSUE TITLE
Certificates are failing to renew

### ISSUE THREAD

**Issue by Marcel0024** [shibayan/keyvault-acmebot#164]
Some certificates are not renewing, where to view the logs?

**Comment by shibayan** [comment]
Check to application insights and azure portal.

**Comment by Marcel0024** [comment]
![image](https://user-images.githubusercontent.com/14852157/93437764-a5638100-f8cc-11ea-9b57-a64ef7439b65.png)

**Comment by shibayan** [comment]
I am not customer support. Do you think this information will help?

**Comment by Marcel0024** [comment]
That's why i kindly asked where to view the proper logs ;(

**Comment by rfcdejong** [comment]
Automatic renewall fails here as well, it never worked either. No time to look into currently, I will manually renew for now.

**Comment by bartholomew-gander** [comment]
+1 from me, it seems that when running manually over UI, code is able to alter Azure DNS records, but on scheduled start it doesn't do so... They remain unchanged, therefore ACME validation fails...
Also did not had time to look into this, as I had to manually renew.

**Comment by shibayan** [comment]
If you are having problems, please create a separate issue following the template. This issue will not be re-opened.
