### ISSUE TITLE
"Cannot read property 'split' of null" - in vue.min.js when accessing add-certificate page when no Azure DNS zones are configured

### ISSUE THREAD

**Issue by Jehoel** [shibayan/keyvault-acmebot#174]
**Describe the bug**

1. I followed the instructions in https://github.com/shibayan/keyvault-acmebot just now (literally within the past 30 minutes) from step 1.
    * Note that I skipped step 4: I did not add IAM access to any Azure DNS zones (yet). The documentation implies this step is optional, especially as the DNS zones I want to use are not hosted in Azure.
2. I accessed https://my-function-app.azurewebsites.net/add-certificate 
* The "DNS Zone" drop-down says "Please select one", but it's empty has an activity spinner that never stops.
* The "DNS Names" box is disabled.
* This error is reported in my browser (Chrome 85)'s console:

```
vue.min.js:6 TypeError: Cannot read property 'split' of null
    at r (punycode.js:98)
    at Object.d [as toUnicode] (punycode.js:454)
    at add-certificate:89
    at eval (eval at Ya (vue.min.js:6), <anonymous>:3:836)
    at wn.vt [as _l] (vue.min.js:6)
    at wn.eval (eval at Ya (vue.min.js:6), <anonymous>:3:744)
    at wn.e._render (vue.min.js:6)
    at wn.r (vue.min.js:6)
    at fn.get (vue.min.js:6)
    at fn.run (vue.min.js:6)
```

 
![image](https://user-images.githubusercontent.com/1693078/95648169-06284880-0a8a-11eb-9e0c-bf2b990725c7.png)

### Update

After I granted the function-app access to an Azure DNS zone it loaded that zone into the drop-down list and no errors were reported.

I've retitled this bug.

**Comment by shibayan** [comment]
Thanks. It doesn't affect the actual use of the software, but there was an error handling issue.

**Comment by emnh** [comment]
I just deployed and I'm getting this error. I tried to add role to give the Function access to resource group and DNS zone, but still getting the error.
