### ISSUE TITLE
Worked perfectly!

### ISSUE THREAD

**Issue by dfahlander** [shibayan/keyvault-acmebot#176]
I just want to 👍  thumbs up this library and share my experience trying the other letsencrypt solutions for azure.

I spend an entire working day trying out other solutions but this one is the only one that works and it was also the easiest to get done with.

My setup is this:
* One root domain (dexie.cloud)
* Wildcard hosts under the same domain (*.dexie.cloud)
* DNS managed in Azure DNS zone. I had this already setup for both dexie.cloud and *.dexie.cloud and had bound it to my web app before I deployed the solution. Was afraid the the root domain wouldn't be possible to get cert for because it has an A record and azure doesn't allow CNAME. However, this turned out not to be a problem!

My experience
1. Spent a few hours reading about various solutions including CloudFlare, CertBot (building some manual script), [AzureWebAppSSLManager](https://github.com/n3wt0n/AzureWebAppSSLManager) and [letsencrypt-azure](https://github.com/sjkp/letsencrypt-azure).
2. From my reading, it seemed I would need to go for [letsencrypt-azure](https://github.com/sjkp/letsencrypt-azure) if I would be able to support wildcard certs so I tried it. Did not work! I tried to follow every step and deploy the solution in its own resource group so it didn't complain about linux resources.
3. Tried [AzureWebAppSSLManager](https://github.com/n3wt0n/AzureWebAppSSLManager). Lots of manual things needed to be done like putting config files in blobs. Had to navigate the source code to understand where files should be located because of missing docs. Still, the result was: nothing happened. Restarted the function. Nothing happened.
4. At last, I tried this solution, keyvault-acmebot and got it working. I had to give myself certificate management rights in the keyvault to be able to import it to the app though. But after that, my wildcard domain just worked!
5. Glad that wildcard domain worked, I wanted to also give it a shot to try it on the root domain even though I didnt think it should work. I tried to get a cert for the root domain using the easy web form to create a cert. I just left the host field blank and it just worked and issued a valid cert for my root domain that I could easily link to my webapp.

The bonus thing with this solution is that the certs goes into the key vault which means they will be possible to use from CDN and frontdoor when I will go for any of those in future. So I am more than satisfied!

*NOTE* Sorry for the **bug** label, but I didn't find a proper issue template. Not able to remove the label.

**Comment by shibayan** [comment]
Thank you. I'm glad to see it worked correctly too. Please create an Issue if you have any feedback.
