### ISSUE TITLE
Encountered an error (ServiceUnavailable) from host runtime.  (Provisioning operation "Action" for type Microsoft.Web/sites)

### ISSUE THREAD

**Issue by wezfaas** [shibayan/keyvault-acmebot#182]
`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (ServiceUnavailable) from host runtime.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"Encountered an error (ServiceUnavailable) from host runtime.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (ServiceUnavailable) from host runtime.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"}]}`

I encountered this error from Step 1 - Deploy Acmebot - For Azure Cloud on one of the Provisioning operations "Action" for type Microsoft.Web/sites.  Provisioning operations "Create" and "Read" for the same type were successful.

And why is the Location locked to "West US"?

**Comment by shibayan** [comment]
This is caused by Function Host not starting properly during deployment. Perhaps you didn't choose the option to create the Key Vault at the same time.

I fixed the ARM template. Enter the base URL of your existing Key Vault and the deployment will be successful.

**Comment by wezfaas** [comment]
Thanks the quick fix.  I ensured create key vault is set to true on my testing, and everything is smooth, on with my next step.  Will test with existing key vault later.
