### ISSUE TITLE
Feature: Add Optional App Role authorization requirement

### ISSUE THREAD

**Issue by seangwright** [shibayan/keyvault-acmebot#189]
**Is your feature request related to a problem? Please describe.**
Giving access to issue certificates to an entire Azure AD org is a bit too permissive for my use case.

**Describe the solution you'd like**
I would like the ability to add an App Role to the Azure AD Application and then require that Role on the principal's claims in the Functions.

Currently, all the checks are for authentication _only_.

```csharp
if (!User.Identity.IsAuthenticated)
{
    return Unauthorized();
}
```

If a role name is specified in the Function's configuration, I would like that to be a required role claim.

```csharp
if (!User.Identity.IsAuthenticated)
{
    return Unauthorized();
}

if (// check if role configuration has a value)
{
    bool hasRole = principal.Claims
        .Where(e => e.Type == "roles")
        .Select(e => e.Value)
        .Any(v => string.Equals(v, "... config value"));

    if (!hasRole)
    {
        return Unauthorized();
    }
}
```

**Describe alternatives you've considered**
If there is another way to limit authorization to specific principals then I'm fine doing that too, but I don't know of any.

**Additional context**
This can also be achieved through declarative attributes, which would require you as the library author to pick the role name or specify the configuration key in the attribute and change the logic of the attribute to only throw an `AuthorizationException` if a value was found in configuration but didn't exist the principal's role claims.

See: https://medium.com/medialesson/role-based-authorization-in-azure-functions-with-azure-ad-and-app-roles-b1fed5714c91

**Comment by seangwright** [comment]
@shibayan I would be happy to work on this as a PR if you have a preference for the architecture/pattern for the implementation.

**Comment by shibayan** [comment]
@seangwright That's an interesting suggestion. First, we need to verify that the App Role in App Service Authentication works as intended.

If there are no problems in operation, I want to implement the following specification

- `Acmebot:RequiredAppRole` app settings (boolean, `1` or `true`)
- I don't want the App Role value to be configurable. Make it a fixed value.
  - eg. `Acmebot.IssueCertificate`

**Comment by seangwright** [comment]
@shibayan Having an explicit role for this project seems fine. It does simplify the project AuthZ logic without putting any real burden on the developer integrating it into their Azure AD setup.
