### ISSUE TITLE
Feature: Integrate with Let's Encrypt Staging Environment

### ISSUE THREAD

**Issue by seangwright** [shibayan/keyvault-acmebot#190]
**Is your feature request related to a problem? Please describe.**
There are [rate limits](https://letsencrypt.org/docs/rate-limits/) on interacting with the Let's Encrypt API. The Staging Environment also has limits [but they are much higher](https://letsencrypt.org/docs/staging-environment/).

**Describe the solution you'd like**
The `/add-certificate` page of the function app could have a checkbox in the form that, when enabled, makes a request to the Staging Environment.

A 'successful' submission would indicate that everything is configured correctly.

**Describe alternatives you've considered**
Since this project uses DNS TXT records to handle challenged to create new certs, it's unlikely that there would be too many issues if the Zone list is populated in the form UI.

However, some more diagnostics and testing would be nice to prevent issues with hitting rate limits.

**Additional context**
- https://letsencrypt.org/docs/rate-limits/
- https://letsencrypt.org/docs/staging-environment/

**Comment by shibayan** [comment]
Acmebot allows you to specify any ACME endpoint. You can use the staging environment by setting up a key from App Settings as follows.

`Acmebot:Endpoint` = `https://acme-staging-v02.api.letsencrypt.org/`

If you have already done this with another endpoint, you will need to remove the `D:\home\.acme` directory and re-register your account.
