### ISSUE TITLE
Create Terraform code

### ISSUE THREAD

**Issue by a8ree** [shibayan/keyvault-acmebot#196]
**Is your feature request related to a problem? Please describe.**
I'd like to deploy this service using Terraform

**Describe the solution you'd like**
The rest of the resources I use in my project are deployed via Terraform and it would be great to have everything deployed in the same way - for supportability

**Describe alternatives you've considered**
I could use an external call to the ARM template but its a bit messy

**Comment by shibayan** [comment]
Do you think it's best to publish to the Registry as a Terraform Module?

**Comment by tplive** [comment]
I was thinking the same thing, and I thought about doing it using a [custom ARM template deployment](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_template_deployment) 
I guess a separate module for acmebot published to the register would be better? :)

**Comment by shibayan** [comment]
I'm still working on it, but I've created a module for Terraform Registry.
https://github.com/shibayan/terraform-azurerm-keyvault-acmebot

**Comment by shibayan** [comment]
Done.
https://registry.terraform.io/modules/shibayan/keyvault-acmebot/azurerm/latest
