### ISSUE TITLE
Support http-01 challenge type

### ISSUE THREAD

**Issue by odegroot** [shibayan/keyvault-acmebot#197]
**Is your feature request related to a problem? Please describe.**
There are some domains where I have control over the web server, but no control over the DNS. It would be great if _keyvault-acmebot_ could use the `http-01` challenge type, to generate certificates for those domains. 🙂

**Describe the solution you'd like**
There should be a config setting / switch somewhere, where the user indicates if they want to use `dns-01` or `http-01`. When you choose `http-01`, then keyvault-acmebot should skip the DNS zone lookup and let the user simply enter the domains directly.
During validation, keyvault-acmebot should serve the challenge token at the challenge URL (http://example.com/.well-known/acme-challenge/…).

The user will need to make sure that such requests are routed to the function app, of course.

**Describe alternatives you've considered**
I could simply not use keyvault-acmebot; generate the certificate with a different tool.

**Additional context**
I might be able to contribute code to implement this.

**Comment by shibayan** [comment]
Since http-01 is difficult to automate without extensions like the App Service, Key Vault Acmebot does not plan to support it.

If you need http-01, you can use the App Service Acmebot, which is Windows-only.
https://github.com/shibayan/appservice-acmebot
