### ISSUE TITLE
IssueCertificate Orchestrator function 'IssueCertificate' failed: The activity function 'CheckIsReady' failed: "ACME domain validation is invalid. Required retry at first.

### ISSUE THREAD

**Issue by asad-c** [shibayan/keyvault-acmebot#198]
All of my certificates are failing to renew across different app services, the following error is from application insights:

Exception while executing function: IssueCertificate Orchestrator function 'IssueCertificate' failed: The activity function 'CheckIsReady' failed: "ACME domain validation is invalid. Required retry at first.
LastError = {
  "type": "urn:ietf:params:acme:error:dns",
  "detail": "During secondary validation: DNS problem: networking error looking up TXT for _acme-challenge.findmyeventplanner.co.uk",
  "status": 400
}". See the function execution logs for additional details. 

Any suggestions to correct this issue?

**Comment by shibayan** [comment]
As the error message would be a temporary network error. I think it will resolve when you try to retry it manually or when it is automatically re-run.

If the error persists, it's probably a problem on the Let's Encrypt side, so please ask on the forum.

**Comment by asad-c** [comment]
I don't think this is a temporary error as it's been happening over the last 30 days affecting 12 different certificates.I've tried running it manually as well. How do I go about doing a re-install? Just delete the resources created and start again?

**Comment by dazinator** [comment]
I hit a similar error with checkisready failing.

In my case, I had forgot to set a `CAA` record on the domain to say that letsencrypt was allowed to act as the certificate authority. I had an older `CAA` record in place on the parent domain limiting it to Digicert. I updated this, and then it seemed to resolve the issue.
