### ISSUE TITLE
Renewal process explaination

### ISSUE THREAD

**Issue by Xat59** [shibayan/keyvault-acmebot#211]
**Describe the bug**
I was able to setup `keyvault-acmebot` and I thank you for your good work.

One thing I am not able to get : how is the renewal process working ? Can you describe how it works ? I didn't see any scheduling, but I need to analyse that part.

Thanks ;)

**Comment by bartholomew-gander** [comment]
Hi @Xat59 , from my analysis of the code, it looks like renewal process is being triggered by standard  Azure Functions Timer trigger. Look at this this file/line for reference: https://github.com/shibayan/keyvault-acmebot/blob/1e6668d9ede26cc4604325dc92c94e51b8f7d50b/KeyVault.Acmebot/Functions/RenewCertificates.cs#L52

You can read more about this topic here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp

Nevertheless I do not see how this is a bug 😄

**Comment by Xat59** [comment]
Thanks a lot @bartholomew-gander ! Indeed that is not a bug, but I had no other choice than bug or feature when I have created the issue.
