### ISSUE TITLE
Thank you ❤

### ISSUE THREAD

**Issue by abergs** [shibayan/keyvault-acmebot#214]
I just wanted to say thank you for creating this project and the appservice version. It makes it A LOT easier to work with LE certificates on Azure. I know from experience open source is a lot of work. want to express my gratitude and that I'm very impressed with what you have created, shared openly and the docs you have written to help others get going.

Have a good 2021!
Best wishes,
Anders in Sweden.

**Comment by ffcruz85** [comment]
I will second this. Something that Azure should be just providing in the first place, and you are covering the gap here for us!
