### ISSUE TITLE
Having problems with AAD Auth

### ISSUE THREAD

**Issue by lcarli** [shibayan/keyvault-acmebot#222]
ERROR MESSAGE: "The reply URL specified in the request does not match the reply URLs configured for the application: 'xxxxx'."

What is the reply URL?

**Comment by lcarli** [comment]
The Key Vault is working fine. The problem is just to authenticate as user.

**Comment by shibayan** [comment]
Did you create an Azure AD configuration in Express from the Authentication settings in Azure Portal? Or did you add a custom domain?

**Comment by lcarli** [comment]
I create as Express following the README. But even with that I'm struggling to authenticate.

**Comment by lcarli** [comment]
@shibayan, there was some issues with my app registration. I recreated and worked! Thank you!
