### ISSUE TITLE
Certificates issued previously have different tags than new certs so GetExpiredCertificates is filtering out those certs and not renewing them

### ISSUE THREAD

**Issue by ChristopherHaws** [shibayan/keyvault-acmebot#224]
**Describe the bug**
We have been using this function app for over a year, and older certs that we have do not have the same tags that new certs have, so when the GetExpiredCertificate function gets called, our previously issued certs are being filtered out and thus they are not getting renewed.

Here is the line I am talking about
https://github.com/shibayan/keyvault-acmebot/blob/master/KeyVault.Acmebot/Functions/SharedActivity.cs#L60

**To Reproduce**
1. Start with a certificate that expires in less than 30 days with the following tags:
    - Issuer = letsencrypt.org
2. Kick off the "RenewCertificates" orchestrator
3. Notice that the certificate does not get renewed

**Additional context**
It would be nice if the function could detect these old certs and renew them using the new behavior (adding the Issue and Endpoint tags so that the function is backwards compatible. For the time being, we manually ran `StaticPage_RenewCertificate` to bypass this issue for our certs.

Old Cert:
![image](https://user-images.githubusercontent.com/5934505/105564035-488e3200-5cd5-11eb-8c5e-755a61a8e474.png)

New Cert:
![image](https://user-images.githubusercontent.com/5934505/105564047-517f0380-5cd5-11eb-8c97-f6e9aac6b9b2.png)

**Comment by shibayan** [comment]
Changed the format of the Issuer tag to support multiple ACME providers.

Implemented automatic migration process and removed it after more than 90 days to take into account the renewal schedule of existing Let's Encrypt certificates, but it may not have been sufficient.

Introduced new issuer tag: https://github.com/shibayan/keyvault-acmebot/releases/tag/v3.1.0
Removed old issuer tag: https://github.com/shibayan/keyvault-acmebot/releases/tag/v3.2.1

In this case, please take manual action or reissue.

**Comment by ChristopherHaws** [comment]
Perhaps adding this info to https://github.com/shibayan/keyvault-acmebot/issues/80 would be helpful to people since we followed those instructions and our renewal process broke.
