### ISSUE TITLE
Add support for Azure DNS Zones spread out over multiple Azure Subscriptions

### ISSUE THREAD

**Issue by rafabu** [shibayan/keyvault-acmebot#234]
**Is your feature request related to a problem? Please describe.**
Our Azure DNS Zones are spread out over several subscriptions for accountability and governance reasons. E.g. one per service tier. However; currently only a single SubscriptionId is supported via the app setting 'Acmebot:AzureDns:SubscriptionId'.

**Describe the solution you'd like**
Add support for iterating through a list of SubscriptionIds when looking up available DNS Zones. Make the setting 'Acmebot:AzureDns:SubscriptionId' accept either a CSV string or JSON array.

**Describe alternatives you've considered**
Provisioning a dedicated ACMEBot per subscription. However; that would make the provisioning of the certificates more challenging, as the correct ACMEBot per subscription would have to be connected to.

**Additional context**
Apart from that everything is working smoothly. Thank you very much for all the effort you put into this neat project.

**Comment by shibayan** [comment]
I have considered this before, but Acmebot is limited to one subscription, because even with permissions in RBAC, processing across subscriptions is complicated for both the implementation and the users.

Since Acmebot is very low cost to operate, I recommend deploying it on a per-subscription basis to limit the permission scope.

See this #103 for previous discussions.

**Comment by TheMorganator** [comment]
Considering that Azure Resource Graph now provides a very quick and easy way to retrieve resources across a large estate, would it be possible to reconsider? You can get all DNS zone resources with just one resource graph call. If Acmebot has permissions across several subscriptions those permissions will be reflected in the query results so no role processing should be necessary.

Even if Acmebot is low cost it still requires some setup with delegation, sign in security etc., so this would be a welcome feature.

Thx!
