### ISSUE TITLE
Issuing certificates for a large number of domains is too slow

### ISSUE THREAD

**Issue by shibayan** [shibayan/keyvault-acmebot#235]
Determine if the ACME Service is taking too long to validate or if there is a problem with the Acmebot process.

**Comment by soderlind** [comment]
@shibayan, do you have a recommended limit? I.e. How many should I add at a time?

**Comment by shibayan** [comment]
In terms of implementation, it can be handled up to the limit of the certification authority without any problems. 

Currently, it takes a long time to write DNS records and to be confirmed by the CA, but I'm planning to improve DNS record writing by concurrent processing.

**Comment by shibayan** [comment]
Most of the processing time is due to the Let' Encrypt confirmation, which is closed because there is little room for speedup.
