### ISSUE TITLE
Support for multiple (azure) subscriptions

### ISSUE THREAD

**Issue by C0smin** [shibayan/keyvault-acmebot#239]
**Describe the solution you'd like**
I would love it if **Acmebot:AzureDns:SubscriptionId** would actually support a comma separated list to have one certificate manager per multiple subscriptions, this also helps keep costs low and less rights spread around. 

**Describe alternatives you've considered**
My current setup is to have a subscription only for DNS, but I would rather keep the domains separate.

**Comment by shibayan** [comment]
Duplicate #234
