### ISSUE TITLE
keyvault-acmebot ADD / Renew certificates does not work since a couple of weeks

### ISSUE THREAD

**Issue by DPOGH** [shibayan/keyvault-acmebot#246]
**Describe the bug**
dear Shbayan,
I implemented the Azure template in December 2020 with **Cloudflare** API and everything worked well until last week.

- trying to **Add** a new certificate do not load the list of domains and do not return any kind of error.
- trying to **Renew** an existing certificate returns the following popup error:

_{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"An error occured while processing your request.","status":500,"detail":"Orchestrator function 'IssueCertificate' failed: The activity function 'Dns01Precondition' failed: \"Service request failed.\r\nStatus: 403 (Forbidden)\r\n\r\nContent:\r\n{\"error\":{\"code\":\"AuthorizationFailed\",\"message\":\"The client 'xxxxxxxxxxxxxxxxxxxxxx' with object id 'yyyyyyyyyyyyyyyyyyyyyyyyyy' does not have authorization to perform action 'Microsoft.Network/dnszones/read' over scope '/subscriptions/kkkkkkkkkkkkkk' or the scope is invalid. If access was recently granted, please refresh your credentials.\"}}\r\n\r\nHeaders:\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nx-ms-failure-cause: REDACTED\r\nx-ms-request-id: REDACTED\r\nx-ms-correlation-request-id: REDACTED\r\nx-ms-routing-request-id: REDACTED\r\nStrict-Transport-Security: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nDate: Mon, 08 Feb 2021 02:01:19 GMT\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nExpires: -1\r\nContent-Length: 391\r\n\". See the function execution logs for additional details.","traceId":"uuuuuuuuuuuuuuu"}_ 

thanks in advance for your help
DP

**Comment by shibayan** [comment]
The error seems to occur because the AzureDns settings are now loaded with priority due to a fix a while ago.

A fix will be released soon, so restarting Azure Functions after the release should fix the problem.

**Comment by shibayan** [comment]
v3.4.4 Released

**Comment by DPOGH** [comment]
Thanks a lot for your prompt reply and resolution.
it works perfectly fine now.

Remember to have a look at the Azure Template 

greetings from France
D.
