### ISSUE TITLE
Support OV and EV certificates

### ISSUE THREAD

**Issue by sandromastronardi** [shibayan/keyvault-acmebot#249]
For a client we are looking into using this nice application for getting the certificates set up, although one thing is missing, that is automated OV or EV certificates from ACME supporting providers that provide these.

It would be nice to be able to have the option to select an authority that provides OV and EV certificates:
like https://docs.digicert.com/certificate-tools/Certificate-lifecycle-automation-index/acme-user-guide/ or https://sectigo.com/resource-library/what-is-acme-protocol

Manual options are possible but pose risks when things are forgotten... having this tool and have it active for ALL certificates would be a real nice feature.

It would be nice to have the option to select the authority when creating a certificate instead of just selecting one... maybe provide the possibility to enable certain authorities in the config, but have the list shown in the UI.

**Comment by shibayan** [comment]
It is essentially an implementation of External Account Binding. EAB support is currently being worked on.

There are no plans to implement ACME endpoint switching. You will need to deploy Acmebot for each endpoint.

**Comment by sandromastronardi** [comment]
Great to hear.
can multiple endpoints use the same certificate vault?

**Comment by shibayan** [comment]
This is possible if you set the access restrictions properly in IAM. However, it is not possible to issue each certificate for the same domain (since the names of the certificates will conflict).
