### ISSUE TITLE
AppSetting with name 'Acmebot:Contacts' is not allowed.

### ISSUE THREAD

**Issue by martijndierckx** [shibayan/keyvault-acmebot#254]
I've tweaked the config file to use names which I can choose...
But now I'm getting an error when trying to deploy:

`AppSetting with name 'Acmebot:Contacts' is not allowed.`

Template:
https://gist.github.com/martijndierckx/461ab4e64fecd3351d42c731af265197

Any ideas on the cause?

**Comment by shibayan** [comment]
This is not an issue with the official ARM Template, so I cannot support it.
