### ISSUE TITLE
Automate propagation of new/updated certificates to Azure CDN

### ISSUE THREAD

**Issue by ryan99fl** [shibayan/keyvault-acmebot#267]
**Is your feature request related to a problem? Please describe.**
When keyvault-acmebot upserts a certificate into an Azure keyvault, that new certificate is not automatically propagated to Azure CDN custom domain HTTPS certificate bindings.

**Describe the solution you'd like**
Automatic trigger of Azure CDN certificate bindings on successful certificate upsert.

**Describe alternatives you've considered**
This functionality is already available by leveraging Azure Automation runbooks. I would like to see it integrated into keyvault-acmebot as a configurable option without the use of Azure Automation runbooks.

**Additional context**
A Posh6 script to trigger the update is available for reference at 
[trigger-Azure-CDN-certificate-update.ps1.txt] (https://github.com/shibayan/keyvault-acmebot/files/6017517/trigger-Azure-CDN-certificate-update.ps1.txt) via https://gist.github.com/HQJaTu/c5695626ba51c6194845fa60913e911b

**Comment by ryan99fl** [comment]
Additionally, perhaps iterate through SANs in newly acquired certificate to determine target Azure CDN custom domains to trigger cert update against.

**Comment by ryan99fl** [comment]
Fast response, thank you for your meaningful work @shibayan :)

**Comment by DL444** [comment]
Azure CDN recently allowed you to select "Latest" as the certificate version. I haven't found an opportunity to test, but I would assume that if you select this the certificate would update automatically.
