### ISSUE TITLE
PreferredChain selection differs from certbot, breaking letsencrypt staging certificate issuance

### ISSUE THREAD

**Issue by gberesford** [shibayan/keyvault-acmebot#271]
**Describe the bug**
When PreferredChain is specified, keyvault-acmebot will choose a certificate chain where **any** certificate in the chain is issued by a cert with the specified name, whereas certbot will choose a certificate chain where the **topmost** certificate in the chain is issued by a cert with the specified name.

This means that, in the cross-signing scenario currently being tested on letsencrypt staging, it's not possible to select the correct certificate chain. As of Feb 18th, the default chain for staging certificates is rooted in an expired cert (deliberately, in order to test a certificate expiration scenario that will occur on prod in the future). The default chain looks like this:
* `(STAGING) Doctored Durian Root CA X3` - *expired*
* `(STAGING) Pretend Pear X1` - signed by Doctored Durian
* `(STAGING) Artificial Apricot R3`
* _Your certificate_

The alternate chain looks like this:
* `(STAGING) Pretend Pear X1` - self-signed
* `(STAGING) Artificial Apricot R3`
* _Your certificate_

So, in order to choose the alternate chain, in certbot you should specify "(STAGING) Pretend Pear X1" as the preferred chain. However, in keyvault-acmebot, specifying that preferred chain still matches the default chain, which is the first one checked, so it doesn't select the alternate chain.

**To Reproduce**
1. Configure `Acmebot:Endpoint` to `https://acme-staging-v02.api.letsencrypt.org/`
2. Configure `Acmebot:PreferredChain` to `(STAGING) Pretend Pear X1`
3. Issue a certificate

Issued certificate chain should look like the alternate chain example above, but it will instead look like the default chain example.

**Additional context**
I think it should just be a case of changing the `defaultX509Certificates.Find(X509FindType.FindByIssuerName, preferredChain, true)` checks in https://github.com/shibayan/keyvault-acmebot/blob/master/KeyVault.Acmebot/Internal/AcmeProtocolClientExtensions.cs to instead check `defaultX509Certificates.FirstOrDefault()?.IssuerName == preferredChain`, (or possibly `LastOrDefault`) but I don't have an environment to test this in at the moment. (I will eventually, but it's likely to be a couple of weeks before I can look at it).

I also don't know if anyone is relying on the existing PreferredChain behaviour.

(Thanks for all your work on keyvault-acmebot - it's a very helpful tool!)

**Comment by shibayan** [comment]
I checked the implementation of certbot and found that it checks the alternate side first when the preferred chain is specified, so I will adjust the implementation.
