### ISSUE TITLE
route53 - appears to delete random existing dns names

### ISSUE THREAD

**Issue by DavidGoodwin** [shibayan/keyvault-acmebot#291]
**Describe the bug**

Using to integrate azure load balancers with domains hosted in AWS route53.

Appeared to work fine, until something triggered it to delete random DNS records within the domain - e.g. requested certificate for beta.<domain-name>

certificate was issued, and I think it then deleted the beta.<domain-name> CNAME/A record when cleaning up ?

Records deleted included those of type A, CNAME, AAAA and TXT. I can't spot much of a pattern covering what it did delete - although it didn't delete all of them.

**To Reproduce**

Use to manage acme certs from domains hosted in route53

**Additional context**

We have logs from cloudtrail showing that the records were deleted.

Is this ...

https://github.com/shibayan/keyvault-acmebot/blame/master/KeyVault.Acmebot/Providers/Route53Provider.cs#L55

triggering the deletion of non-txt records?

**Comment by DavidGoodwin** [comment]
https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListResourceRecordSets.html - I think the code is just retrieving records from the given name ... in ASCII order ... it's not filtering.

**Comment by shibayan** [comment]
Thank you for your feedback. The behavior of the API seems a bit strange. Filtering is done on the client side.

**Comment by DavidGoodwin** [comment]
thanks for the speedy fix; being ignorant ... how do i go about getting the fixed version deployed into my azure instance?

**Comment by shibayan** [comment]
Don't worry. Soon I will release a new version and the latest version will be deployed automatically.

**Comment by DavidGoodwin** [comment]
@shibayan is there a version string or something I can check and/or some process to go through to ensure an update has been applied? 

I'm hesitant to re-enable the Function App until I know the fix is deployed.

Sorry if this is a really obvious newbie question, we're new to Azure (and Function Apps).  I've had a rummage around through the Portal and can't see anything .... but it's probable I don't know where to look.

**Comment by agustinsilvano** [comment]
I'm waiting to re-run the function but I want to know 100% secure that the code with the fix is in the latest deployment. 

Because I can't fall back in the same DNS error again.

Thanks!

Agustín.

**Comment by shibayan** [comment]
It's best to have them try it in a hosted zone for testing, but it do send the version to Application Insights so they can check the version in production.

If you open the latest telemetry from Transaction search, you should find a property called Application version.

![image](https://user-images.githubusercontent.com/1356444/111855247-17de1800-8967-11eb-9e8b-51116b2abd3d.jpeg)
