### ISSUE TITLE
Resources Records returned by AWS aren't filtered.

### ISSUE THREAD

**Issue by agustinsilvano** [shibayan/keyvault-acmebot#294]
**Description**
Hey!
I've configured and deployed the application on Azure with Route 53 as a DNS provider (who already had the domain properly configured and have many zones inside). Some minutes after that, we noticed that many of our sites were using the wrong certificate (and showing untrusted domain on the browser).  This is because the DNS config on Route53 had removed some entries.

I've confirmed that was the application that deletes the entries in the DNS configuration because I saw the AWS event logs and see the same time (hour, minute and second) for the acme-bot TXT creation and the deletion of the other existent records (CNAME, A, TXT).

I think that the issue is the behavior of the method _ListResourceRecordSetsAsync_ on the _AmazonRoute53Client_.
In the _Route53Provider.cs_ file in the method _DeleteTxtRecordAsync_ in line 65, the _ListResourceRecordSetsRequest_ appears to be ok (filtering by TXT record type and desired record name); but the response that AWS provides contains registries that don't match with the "filter" provided before.

![photo](https://user-images.githubusercontent.com/29497274/111829350-58885380-88cb-11eb-9336-90cb0487015c.png)
Here is a screenshot of the response from AWS Route53 SDK (while debugging the solution), which contains: A records, CNAME records, and TXT records.

The response had 29 entries while the response should have 0 entries(because there is no entry that matches the requested filter).

**To Reproduce**
NA.

**Environment (please complete the following information):**
 No related with the environment, same behavior locally and deployed in Azure. 

**Additional context**
Hotfix: What I made was to filter again (using Linq) the _ResourceRecordSets_ property of the _listResponse_ variable and use that filtered list to build the _changes_ variable as shown below. 

```
var filteredRecords = listResponse.ResourceRecordSets.Where(a => a.Type == RRType.TXT && a.Name == recordName).ToList();

var changes = filteredRecords
                       .Select(x => new Change { Action = ChangeAction.DELETE, ResourceRecordSet = x })
                       .ToList();

var request = new ChangeResourceRecordSetsRequest(zone.Id, new ChangeBatch(changes));
```

I know that the error appears to be from AWS SDK but this should be a nice validation to avoid undesired behaviors in the DNS configuration.

Just let me know if I made some mistakes in the process.

Agustín.

**Comment by DavidGoodwin** [comment]
probably duplicates of #291 and #292

**Comment by shibayan** [comment]
This problem has been fixed in the latest release.
