### ISSUE TITLE
Error when viewing Add Certificate page

### ISSUE THREAD

**Issue by cfredette** [shibayan/keyvault-acmebot#299]
After deploying and adding proper permissions to DNS zone I receive a [object Object] when DNS Zone dropdown is populating.

Exception while executing function: GetDnsZones_Orchestrator Orchestrator function 'GetDnsZones_Orchestrator' failed: The activity function 'GetZones' failed: "DNS Provider is not configured. Please check the documentation and configure it.". See the function execution logs for additional details.

**Comment by cfredette** [comment]
I figured it out.. I suggest adding better instructions on adding the application setting for your DNS provider within the function application configuration settings.

**Comment by mserbi** [comment]
Did you remember how did you fixed it? I'm having the same issue.

**Comment by sethidden** [comment]
Remember that on the Application Settings page you need to click save (diskette icon) after adding the setting :)
So:
1. Add setting, fill out 2 fields in sidebar that pops up, press OK
2. **Press save in the header of the main view**
Basically if you hard refresh and the setting you've added is gone you've forgot to save

**Comment by MattPark** [comment]
What is the correct role that needs to be set on the DNS zone?  Same as the connectivity group?
