### ISSUE TITLE
Renew certificate while maintaining certificate keys

### ISSUE THREAD

**Issue by adamskibickipd** [shibayan/keyvault-acmebot#304]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem.

**Describe the solution you'd like**
I'd like to have ability to renew certificate while maintaining certificate keys. Reason: mobile app uses certificate public key while connecting to API under a certificate and i don't want to change public key in mobile app with each certificate renewal.

**Describe alternatives you've considered**
I started working as DevOps recently and i was given issue described above to handle and for now i don't know other alternatives than writing my own scripts to handle certificate renewal.

**Comment by shibayan** [comment]
#305 improvements will reuse existing policies when renewing certificates, which can be accomplished using the REST API until a GUI is added.

https://docs.microsoft.com/en-us/rest/api/keyvault/updatecertificatepolicy/updatecertificatepolicy#keyproperties

**Comment by adamskibickipd** [comment]
Thanks, i confirmed that it works as intended.
