### ISSUE TITLE
New certificate fails when DNS lock is enabled

### ISSUE THREAD

**Issue by silviodc** [shibayan/keyvault-acmebot#310]
Why is it necessary to remove the dns lock preventing other from delete?
**Describe the bug**
Service request failed.
 Status: 409
cannot perform delete operation because following scope(s) are locked
Please remove the lock and try again.
`{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
  "title": "An error occured while processing your request.",
  "status": 500,
  "detail": "Orchestrator function 'IssueCertificate' failed: The activity function 'Dns01Authorization' failed: \"Service request failed.\r\nStatus: 409 (Conflict)\r\n\r\nContent:\r\n{\"error\":{\"code\":\"ScopeLocked\",\"message\":\"The scope '/subscriptions/*********' cannot perform delete operation because following scope(s) are locked: '/subscriptions/*******'. Please remove the lock and try again.\"}}\r\n\r\nHeaders:\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nx-ms-failure-cause: REDACTED\r\nx-ms-request-id: REDACTED\r\nx-ms-correlation-request-id: REDACTED\r\nx-ms-routing-request-id: REDACTED\r\nStrict-Transport-Security: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nDate: Sun, 25 Apr 2021 22:19:50 GMT\r\nContent-Length: 456\r\nContent-Type: application/json; charset=utf-8\r\nExpires: -1\r\n\". See the function execution logs for additional details.",
  "traceId": "00-2b72276cecc4e*****9f3b-c64b2a71677ad545-00"
}`

**To Reproduce**
1. Create a lock on DNS Zone to not allow other to delete
2. Try to issue a new certificate

**Comment by shibayan** [comment]
See also https://github.com/shibayan/keyvault-acmebot/issues/195#issuecomment-731100849
