### ISSUE TITLE
HTTP-Challenge

### ISSUE THREAD

**Issue by lcarli** [shibayan/keyvault-acmebot#315]
Is it possible to challenge thru HTTP? 
If we are responsible for the website but not for the DNS provider...?

**Comment by GeorgDangl** [comment]
I think that would be the https://github.com/shibayan/appservice-acmebot project then. This repository is for managing certificates via DNS, the other one works directly with AppService😀

**Comment by shibayan** [comment]
HTTP Challenge is strongly dependent on the web server, so I do not plan to implement it in this application. https://github.com/shibayan/keyvault-acmebot/issues/197#issuecomment-735797980

As @GeorgDangl said, HTTP Challenge is available in App Service Acmebot if it is an App Service Windows.
