### ISSUE TITLE
Doesn't handle durable function 202 response with large number of zones

### ISSUE THREAD

**Issue by timja** [shibayan/keyvault-acmebot#328]
**Describe the bug**

**To Reproduce**
1. Add a number of DNS zones that your SP has access to, mine has 27
2. Open developer tools
3. Monitor the call to `/api/dns-zones`
4. It _may_ return a 202 accepted response instead of 200 with a url to fetch the result

In my case the response was:

```
{
  "id": "******",
  "statusQueryGetUri": "https://******.azurewebsites.net/runtime/webhooks/durabletask/instances/********?taskHub=DurableFunctionsHub&connection=Storage&code=******==&returnInternalServerErrorOnFailure=true",
  "sendEventPostUri": "https://********.azurewebsites.net/runtime/webhooks/durabletask/instances/******/raiseEvent/{eventName}?taskHub=DurableFunctionsHub&connection=Storage&code=********==",
  "terminatePostUri": "https://********.azurewebsites.net/runtime/webhooks/durabletask/instances/******/terminate?reason={text}&taskHub=DurableFunctionsHub&connection=Storage&code=********==",
  "purgeHistoryDeleteUri": "https://acmedcdcftappsprod.******.net/runtime/webhooks/durabletask/instances/********?taskHub=DurableFunctionsHub&connection=Storage&code=********==",
  "restartPostUri": "https://********.azurewebsites.net/runtime/webhooks/durabletask/instances/******/restart?taskHub=DurableFunctionsHub&connection=Storage&code=******=="
}
```

and the response from the durable task status query url was wrapped like so:

```json
{
  "name": "GetDnsZones_Orchestrator",
  "instanceId": "***",
  "runtimeStatus": "Completed",
  "input": null,
  "customStatus": null,
  "output": [
    "my-zone",
    "x27...",
  ],
  "createdTime": "2021-06-01T10:08:14Z",
  "lastUpdatedTime": "2021-06-01T10:09:18Z"
}
```

**Environment (please complete the following information):**
 - Certificate Type: [e.g. Zone Apex, Sub-domain, Wildcard]
 - Certificate Deploy Target: [e.g. App Service] 

**Additional context**

**Comment by shibayan** [comment]
What DNS provider did you use?

**Comment by timja** [comment]
Azure DNS, it's working currently seems like we get that response sometimes when it just gets a bit slow

**Comment by shibayan** [comment]
Azure REST API may be slow to respond, which can be checked with App Insights. If the REST API response is slow, there is no way to improve it.

**Comment by timja** [comment]
Can’t this app switch to using the durable response instead? The dns zones api returned a 202 with a url to fetch the result later and when I fetched the result all the data was there

**Comment by shibayan** [comment]
I have not implemented it to handle 202, but you can create a pull request to improve it.
Alternatively, it is recommended that you use the REST API to issue certificates.

**Comment by timja** [comment]
Thanks will see how we go, may come back later with a PR.

In general it works fine, but when I raised this issue I tried a few times over a 30minute period and I wasn't able to get it to load
