### ISSUE TITLE
when webhook (teams) fails there is no logging of the reason

### ISSUE THREAD

**Issue by sandromastronardi** [shibayan/keyvault-acmebot#329]
I have configured a microsoft Teams webhook to receive messages but for some reason it causes a 400 response for teams...
I looked at the code and replicated it with postman, but that works.... the problem is I can't see the content of the 400 error.
I have it working for slack but I need it in teams but don't know what to do to fix it.

**To Reproduce**
Setup a webhook for teams, but not sure why it fails now, logging is missing.

**Environment (please complete the following information):**
Azure Dns
LetsEncrypt
Teams

**Comment by shibayan** [comment]
Now that I understand the problem, I will change it to send a warning to Application Insights when the webhook result is not normal.

Please share if you find the cause from Application Insights logs. I will fix it if possible.

**Comment by sandromastronardi** [comment]
yes, great, thanks... I will let you know... let you know me when the package is updated on your blob storage?

**Comment by shibayan** [comment]
I have already released the latest version, the failure log should be output after restarting the corresponding Azure Function.

**Comment by shibayan** [comment]
Once you have successfully captured the webhook error, create another issue.
