### ISSUE TITLE
Uploads cert chain in reverse order from what nginx ingress controller expects

### ISSUE THREAD

**Issue by bsomes** [shibayan/keyvault-acmebot#340]
**Describe the bug**
Acmebot uploads the certificate chain to Keyvault in the order
-----ROOT-----
-----INTERMEDIATE CERT-----
-----SERVER CERT-----
but when I try to use this as a TLS secret in kubernetes for the NGINX ingress controller, it expects the certs in the order
-----SERVER CERT-----
-----INTERMEDIATE CERT-----
-----ROOT-----

I think the bot is reversing the order of the certificates and some applications can't handle it.

**To Reproduce**
1. Make a cert for some domain using Let's Encrypt
2. Start a kubernetes cluster (AKS or Minikube will work just fine)
3. Start up any old hello world deployment in kubernetes.
4. Install the ingress-nginx helm chart
5. Download the cert with the private key from Keyvault and convert to PEM format if it's not already in that format
6. Make a tls secret in kubernetes with tls.cert and tls.key both being set to the converted file from Keyvault
7. Add an ingress to your hello world app with SSL termination using the tls secret
 The error message just says that the server's certificate and the private key don't match but if you reverse the order of the certs it works. 

**Environment (please complete the following information):**
 - Certificate Type: Wildcard from Let's Encrypt
 - Certificate Deploy Target: AKS as TLS secret for use in NGINX Ingress Controller

**Additional context**
I believe the way NGINX expects the certificates is the "correct" way to order the chain but other servers (like Golang http.ListenAndServeTLS) seem to handle it just fine.

**Comment by shibayan** [comment]
This is not remediable by Acmebot as it is a problem with the way Key Vault works. Please check the related discussion. #210
