### ISSUE TITLE
Improve docs for route53 for required permissions

### ISSUE THREAD

**Issue by pietzschke** [shibayan/keyvault-acmebot#346]
It would be nice to have the required permissions for the access to route53 in the docs too:
```json
"route53:ChangeResourceRecordSets",
"route53:ListResourceRecordSets",
"route53:ListHostedZones"
```

For more granular permissions onto specific hosted zone:
```json
{
     "Sid": "VisualEditor1",
     "Effect": "Allow",
     "Action": [
         "route53:ChangeResourceRecordSets",
         "route53:ListResourceRecordSets"
      ],
     "Resource": "arn:aws:route53:::hostedzone/YOUR_ZONE_ID"
},
{
      "Sid": "VisualEditor2",
      "Effect": "Allow",
      "Action": "route53:ListHostedZones",
      "Resource": "*"
  }
```

**Comment by shibayan** [comment]
Thanks for the feedback, I've added the details to the wiki.
https://github.com/shibayan/keyvault-acmebot/wiki/DNS-Provider-Configuration#amazon-route-53

It would be great if you could use [Discussion](https://github.com/shibayan/keyvault-acmebot/discussions/new) to make suggestions next time.
