### ISSUE TITLE
Please Update the Ajax libraries on the sites

### ISSUE THREAD

**Issue by BradMarwood** [shibayan/keyvault-acmebot#359]
Scanning a deployed version of the site, the ajax library from 
https://cdnjs.cloudflare.com/ajax/libs/vue/3.0.2/vue.global.prod.js
is listed as vulnerable at this point.

I did minor testing with the following version and didn't see any issue.
https://cdnjs.cloudflare.com/ajax/libs/vue/3.2.11/vue.global.prod.min.js

**Comment by shibayan** [comment]
Thanks for the feedback. I will update the library to the latest version in the next release.
