### ISSUE TITLE
Exception of type 'System.Net.Http.HttpRequestException' was thrown.

### ISSUE THREAD

**Issue by johnnycchapman** [shibayan/keyvault-acmebot#375]
**Describe the bug**
Our engineering team set up a Key Vault acmebot in Azure US Government cloud. The deployment ran successfully and we made sure to enable authentication from the advanced settings. When trying to create new certificates using our https://YOUR-FUNCTIONS.azurewebsites.net/add-certificate link, we got the error below: 

_Orchestrator function 'IssueCertificate' failed: The activity function 'Dns01Authorization' failed: "Exception of type 'System.Net.Http.HttpRequestException' was thrown.". See the function execution logs for additional details._

I referred to issues [#188](https://github.com/shibayan/appservice-acmebot/issues/188) and [#189](https://github.com/shibayan/appservice-acmebot/issues/189) for some guidance, but was not able to draw conclusions to solve this issue. 

**To Reproduce**
1. Go to https://func-letsencrypt-25p7.azurewebsites.us/add-certificate
2. Click on 'online15.net' DNS zone
3. Add DNS names and Click 'Submit'

**Environment:**
 - Azure US Government Cloud
 - Certificate Type: Sub-domain
 - Certificate Deploy Target: App Service

**Additional context**
We are using GoDaddy to host our DNS servers

**Comment by shibayan** [comment]
The error is probably in the execution of the GoDaddy API.

If you check the Dependencies under Failures in Application Insights deployed with Acmebot, you should be able to see which API failed. Please share if you can.

The GoDaddy Provider implementation is currently being improved, but it is unclear if it will improve as it may be a separate issue.

**Comment by johnnycchapman** [comment]
We just checked the **Dependencies** under the **Failures** tab and found that it was the GoDaddy API. It was generating a error reading: HTTP: PATCH api.godaddy.com/v1/domains/online15.net/records

So now that we have found that is the source of the issue, do you have any suggestions remediate it?

**Comment by shibayan** [comment]
Thank you. Do you know what the HTTP status code is for that PATCH request? It's probably 400 or 404.

It is possible that this has been improved in the latest release, so it is worth trying after restarting Azure Functions from the Azure Portal. (The latest release has been tested by me on GoDaddy)

**Comment by johnnycchapman** [comment]
The status code appeared to be 422. 

Also, I restarted the function app and the new release fixed the error we were getting. Thank you for your help!
