### ISSUE TITLE
add-certificate never completing with Godaddy provider V3.6.12

### ISSUE THREAD

**Issue by brboyer** [shibayan/keyvault-acmebot#380]
add-certificate failing with  Godaddy provider V3.6.12
DELETE /v1/domains/****.com/records/TXT/_acme-challenge.qaobjsvceu01

Result code	404

**Comment by shibayan** [comment]
I changed the `PropagationSeconds` to 600 seconds because GoDaddy only allows you to set the TTL to a minimum of 600 seconds. So you will have to wait more than 10 minutes for `add-certificate`.
