### ISSUE TITLE
It's possible to deactivate the identity provider authentication?   

### ISSUE THREAD

**Issue by ankit-kumar-mck** [shibayan/keyvault-acmebot#389]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shibayan** [comment]
Since the error message shows a cast error, there is most likely a problem with the post data being passed to the API.

Please make sure that you are passing `DnsNames` as an array correctly.
