### ISSUE TITLE
add-certificate shoud redirect to dashboard on request

### ISSUE THREAD

**Issue by KimTEriksson** [shibayan/keyvault-acmebot#405]
Hi!

The old way of adding certificate was by going to https://certificatesite.azurewebsites.net/add-certifcate but that page now throws an 404
Found that the new site is https://certificatesite.azurewebsites.net/dashboard.

Also the docs should be updated

Thx!

**Comment by shibayan** [comment]
The documentation has been updated. There are no plans to add a redirection process.
