### ISSUE TITLE
Step 5 doesnt make sense

### ISSUE THREAD

**Issue by bbakermmc** [shibayan/keyvault-acmebot#41]
> Assign DNS Zone Contributor role to Azure DNS

Do you mean to the Function App, or the AAD App/Service Principal?

**Comment by shibayan** [comment]
Assign `DNS Zone Contributor` role to the created function app.

![image](https://user-images.githubusercontent.com/1356444/64353952-871c4180-d039-11e9-90e7-203cd9c39be3.png)

**Comment by bbakermmc** [comment]
@shibayan Thanks.
Does this also make the bindings for sites, or does this just create/renew the certs, and then we would need to manually create the bindings using the "Import Key Vault Cert"

**Comment by shibayan** [comment]
You only need to import the certificate from Key Vault to App Service using "Import Key Vault Cert" for the first time only.

After that, when the Key Vault is updated, the App Service certificate and binding are automatically updated.

**Comment by bbakermmc** [comment]
@shibayan Great.  Thanks.  Only enhancement I could see would be to show a check list of Slots/AppServices on the page so it could create the bindings :)  I know its not hard to do but if it can save some time :)

**Comment by shibayan** [comment]
Thank you. But since it's an certificates issuer, it's a concept that you can use the Azure portal to manage bindings.
