### ISSUE TITLE
Access denied when writing to filesystem on linux

### ISSUE THREAD

**Issue by RedTaz** [shibayan/keyvault-acmebot#410]
**Describe the bug**
When deploying the function app to a linux app service the following exception is thrown while issuing a certificate.

> Exception while executing function: IssueCertificate Orchestrator function 'IssueCertificate' failed: The activity function 'Order' failed: "Access to the path '/home\.acme\directory.json' is denied."

**To Reproduce**
1. Clone repository
2. Create Linux Function App (Consumption Plan)
3. Configure Minimum Application settings (*)
4. Use Visual Studio to publish Function App
5. Enable Managed Identity on Function App
6. Enable Authentication with Microsoft Provider
7. Add IAM for Key Vault
8. Add IAM for DNS
9. Browse to `https://<Function App>/dashboard`
10. Click Add
11. Select DNS Zone
12. Enter any DNS name
13. Error is shown in browser Alert: `Access to the path '/home\.acme\directory.json' is denied`

(*) Settings Configured
- Acmebot__AzureDns__SubscriptionId
- Acmebot__Contacts
- Acmebot__Endpoint
- Acmebot__VaultBaseUrl

**Environment**
 - Certificate Type: Any
 - Certificate Deploy Target: Linux Consumption Plan

**Comment by shibayan** [comment]
Acmebot is not designed to work with Linux Consumption. You need to use the official ARM Template or Terraform Module.

**Comment by RedTaz** [comment]
I have a simple fix for this but I can't figure out how to contribute directly.

These lines can be updated to use forward slash instead of backslash.

https://github.com/shibayan/keyvault-acmebot/blob/5c0d77c203f26cd7565982a178c47c69be4e4d16/KeyVault.Acmebot/Internal/AcmeProtocolClientFactory.cs#L124
https://github.com/shibayan/keyvault-acmebot/blob/5c0d77c203f26cd7565982a178c47c69be4e4d16/KeyVault.Acmebot/Internal/AcmeProtocolClientFactory.cs#L138
https://github.com/shibayan/keyvault-acmebot/blob/5c0d77c203f26cd7565982a178c47c69be4e4d16/KeyVault.Acmebot/Providers/TransIpProvider.cs#L228
https://github.com/shibayan/keyvault-acmebot/blob/5c0d77c203f26cd7565982a178c47c69be4e4d16/KeyVault.Acmebot/Providers/TransIpProvider.cs#L243

As per docs https://docs.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar?view=net-6.0

> If you prefer to hard-code the directory separator character, you should use the forward slash (/) character. It is the only recognized directory separator character on Unix systems, as the output from the example shows, and is the AltDirectorySeparatorChar on Windows.

**Comment by shibayan** [comment]
Only Windows Consumption Plan is supported, as it leads to higher maintenance costs. There is no advantage to supporting Linux Consumption Plan.

If a pull request is created, it will not be accepted.

**Comment by RedTaz** [comment]
No problem, I'm happy to fork the code.

You may want to update the Feature Support section of the readme in that case:

> All Azure App Services (Web Apps / Functions / Containers, regardless of OS)

**Comment by shibayan** [comment]
Obviously, the README refers to the App Service that uses the certificate, so there is no need to update it.
