### ISSUE TITLE
Bicep Version of template deployment

### ISSUE THREAD

**Issue by matsest** [shibayan/keyvault-acmebot#420]
**Is your feature request related to a problem? Please describe.**
First of all, thanks for a great piece of software. 

After deploying I found a few things that I've changed when deploying. If these are something you would consider as well, I'm happy to contribute with a PR.

- Set tags on resources
- Be able to redeploy resources
- Set location on resources
- Simpler authoring of template

**Describe the solution you'd like**

Would you consider these changes for a PR? You can see the changes in my branch [here](https://github.com/matsest/keyvault-acmebot/tree/bicep).

- [Bicep](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview) version of the template + generated ARM template
  - `bicep build azuredeploy.bicep` generates `azuredeploy.json`
- Change names of resources to be declarative (only dependent on parameters, not deployment names) to allow redeploy to existing resources
- Add location param (defaults to resourcegroup().location)
- Add tags param to allow settings tags on deployment

**Describe alternatives you've considered**

N/A

**Additional context**

Bicep CLI version 0.4.1008 (223b8d227a)

**Comment by shibayan** [comment]
Thanks for the feedback.

Bicep version of azuredeploy.json and work to make it available as a module is in progress. It will be released in the near future.
