### ISSUE TITLE
404 when going to the ui root 

### ISSUE THREAD

**Issue by jsblake** [shibayan/keyvault-acmebot#421]
**Is your feature request related to a problem? Please describe.**

It's not a show stopper but it is a quality of life issue: when going to https://your-acmebot-instance.azurewebsites.net (or https://youracmebotcustomdomain.com) directly you get a 404 error

**Describe the solution you'd like**

Going to / should either just show the dashboard or redirect you to the dashboard

**Describe alternatives you've considered**
Putting acmebot's UI behind an App Gateway/Front Door and using URL rewriting or redirects would solve this, but those are inelegant and introduce cost if you don't have an existing AppGw you can use

**Additional context**
bonus points if the dashboard had links back to the github project, documentation wiki (or had documentation built in), etc

**Comment by shibayan** [comment]
The URL of the dashboard will be changed in the official v4 release
