### ISSUE TITLE
Feature request: ability to modify existing cert

### ISSUE THREAD

**Issue by jsblake** [shibayan/keyvault-acmebot#425]
**Is your feature request related to a problem? Please describe.**
It would be helpful to modify a certificate that is already issued--either adding new SANs, key size, key re-use, or any other options

**Describe the solution you'd like**
In addition to being able to just hit the renew button on an existing certificate, it would be great if an existing certificate could be modified. I understand under the hood this would be re-issuing a new cert, but issuing the new cert and saving it to the same name would allow any existing downstream services to use the new cert without reconfiguration 

**Describe alternatives you've considered**
The only other alternative is to manage more individual certs than necessary

**Comment by shibayan** [comment]
This is something that can be easily done by editing the Key Vault Certificate issuance policy from Azure Portal or Azure CLI.

There is no need to take any special action in Acmebot. There are no plans to add the ability to change Key Vault Certificate policies in the dashboard.
