### ISSUE TITLE
Automatic update of multi domain certificate failed

### ISSUE THREAD

**Issue by soderlind** [shibayan/keyvault-acmebot#428]
Automatic update of multi domain certificate failed. Reason: one of the domains in the cert didn't point to the service anymore (the domain is deleted), resulting in the following error message:

```
Orchestrator function 'RenewCertificate_Orchestrator' failed: The orchestrator function 'IssueCertificate' failed: 
"The activity function 'Dns01Precondition' failed: "
The delegated name server is not correct. DNS zone = DOMAIN.no, 
Expected = ns1-02.azure-dns.com,ns2-02.azure-dns.net,ns3-02.azure-dns.org,ns4-02.azure-dns.info, Actual = ". 
See the function execution logs for additional details.". See the function execution logs for additional details
```

**Environment:**
 - Certificate Type: Zone Apex and Sub-domain
 - Certificate Deploy Target: Azure Front Door

**Fix?**

When a domain in a multi domain certificate fails, ignore the domain and create a certificate for the rest of the domains.

**Comment by shibayan** [comment]
If you want to remove unwanted domains from a multi-domain certificate, remove the unwanted domains from the Key Vault certificate issuance policy.

https://docs.microsoft.com/en-us/azure/key-vault/certificates/about-certificates#certificate-policy

**Comment by soderlind** [comment]
The problem here was that I was not aware that the domain was deleted. Discovered it when the cert wasn't updated for the other domains and their service failed.

**Comment by shibayan** [comment]
It is difficult to ignore and automatically renew a domain that has become an error for the sake of certificate security. That would invalidate the certificate even for a temporary DNS error.

It is important to check your webhook settings, your Key Vault certificate expiration policy settings, and the expiration notification email sent by Let's Encrypt to know that the certificate renewal has failed.
