### ISSUE TITLE
Can't revoke multi domain certificate.

### ISSUE THREAD

**Issue by soderlind** [shibayan/keyvault-acmebot#429]
Same reason as in #428, one of the domains in the cert didn't point to the service anymore (the domain is deleted).

When I try to revoke the multi domain certificate I get the following error (sorry, it's a screenshot, the modal wouldn't let me copy the error message):

<img width="317" alt="revoke-cert" src="https://user-images.githubusercontent.com/1649452/146901300-ae63431f-b86e-4fd4-b291-a79ab9a27cd2.png">

**Environment (please complete the following information):**
 - Certificate Type: Zone Apex and Sub-domain
 - Certificate Deploy Target: Azure Front Doot

**Comment by shibayan** [comment]
According to the error message, the problem seems to be caused by attempting to revoke an expired certificate. There is an error handling problem that will be addressed, but it seems that Let's Encrypt specifications do not allow revocation of expired certificates.
