### ISSUE TITLE
Name of resources

### ISSUE THREAD

**Issue by bbakermmc** [shibayan/keyvault-acmebot#44]
Is there anyway we could pass in overrides to better name the resources.  We dont abide by the prefix + guid.

**Comment by bbakermmc** [comment]
It might be better to just allow people to create a function app with your code, we don't necessarily need the plan service either we can use one of our existing ones since usage would be super low.

So if you have an example of just deploying the function app code from source that might work :)

**Comment by shibayan** [comment]
There is no plan to change this to prevent name conflict during deployment.
