### ISSUE TITLE
ARM template - select region

### ISSUE THREAD

**Issue by dazinator** [shibayan/keyvault-acmebot#442]
**Is your feature request related to a problem? Please describe.**
When deploying using the ARM template, the azure region to deploy to is not editable, and is set to the location of the selected resource group.

![image](https://user-images.githubusercontent.com/3176632/148731717-e38f5e4a-7471-47bd-b898-3816e1e2a501.png)

I can see how in most cases this would make a sensible default, however technically resource groups can contain resources in other regions, and there should be no restriction on this.

**Describe the solution you'd like**
I'd like for this parameter to allow you to select a region to deploy the function into.

**Describe alternatives you've considered**
Editing the template / creating a custom template with this param changed to the region I want for the sake of this particular deployment.

**Additional context**
My resource group was created in a region, I then ended up moving all of its resources to another region, the resource group location / region itself is now irrelevent to me, and I want to deploy acme bot into a different region that the resource group location.

**Comment by dazinator** [comment]
There is an example of how to do this here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/resource-location?tabs=azure-powershell

**Comment by shibayan** [comment]
I have made it work this way to simplify the deployment procedure. If you need customization, you can create your own resources.

**Comment by dazinator** [comment]
Ok thanks
