### ISSUE TITLE
Update REST API wiki page

### ISSUE THREAD

**Issue by booyaa** [shibayan/keyvault-acmebot#443]
**Describe the bug**

[add-certificate](https://github.com/shibayan/keyvault-acmebot/wiki/REST-API#add-certificate) endpoint only works if you add a header "Content-type: application/json". Otherwise you get a HTTP 400 error (Bad request)

**To Reproduce**

`curl -X POST -d '{"DnsNames": ["contoso.com", "www.contoso.com"]}' .../api/certificate`

**Environment (please complete the following information):**
 - Certificate Type: Any
 - Certificate Deploy Target: Any

**Additional context**

To resolve

`curl -X POST -H 'Content-type: application/json' -d '{"DnsNames": ["contoso.com", "www.contoso.com"]}' .../api/certificate`

If you want to keep the single line HTTP plain text notation...

```sh
POST /api/certificate
Content-type: application/json
```

**Comment by shibayan** [comment]
Thanks for the feedback. I fixed it.
https://github.com/shibayan/keyvault-acmebot/wiki/REST-API#common-headers
