### ISSUE TITLE
Avoid hitting the max request limit (HTTP status code 429( in Let's Encrypt

### ISSUE THREAD

**Issue by booyaa** [shibayan/keyvault-acmebot#454]
**Is your feature request related to a problem? Please describe.**
When ordering a certificate if you make too many requests the Let's Encrypt API will send HTTP status code 429. If you ignore this, you will be blocked from making requests for a week. Currently, Key Vault Acmebot retries if it gets a fail including 429s.

**Describe the solution you'd like**
It would be good to stop before you get 429 and post on the Teams webhook that we're near the limit.

**Describe alternatives you've considered**
We should have the option to either fail the request (no retry) or add an exponential backoff i.e. 2nd attempt is 60 seconds, 3rd attempt is 120 seconds, 4th attempt is 240 seconds, etc

**Additional context**
Here's what happened in the code, when we hit the limit:

- 14:04:12.902 - Order function was called 
- 14:09:13.085 - HTTP /acme/new-nonce - HTTP status 200
- 14:09:13.292 - POST /acme/new-order - HTTP status 429
- 14:09:16.360 - POST /acme/new-order - HTTP status 429
- 14:09:21.004 - POST /acme/new-order - HTTP status 429
- 14:09:29.286 - POST /acme/new-order - HTTP status 429
- 14:09:45.461 - POST /acme/new-order - HTTP status 429

**Comment by shibayan** [comment]
Acmebot already have exponential backoff implemented, and since the Let's Encrypt endpoint also has a per-second rate limit on a per-IP-address basis, we will continue to retry with the current implementation.
