### ISSUE TITLE
Deploying to Azure

### ISSUE THREAD

**Issue by desmphil** [shibayan/keyvault-acmebot#456]
I currently use an old version in another tennant and it works just fine.

Im trying to install a new version for another customer and i get this error

`{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "The data is not valid (Invalid values supplied for Azure Files related app settings.).",
        "details": [
            {
                "message": "The data is not valid (Invalid values supplied for Azure Files related app settings.)."
            },
            {
                "code": "BadRequest"
            },
            {}
        ]
    }
}
`
![2022-03-07 09_42_59-Operation details - Microsoft Azure and 5 more pages - EPQ - Microsoft​ Edge Bet](https://user-images.githubusercontent.com/48382849/157056064-b2712731-56d2-4d05-beed-2e22c4803646.png)

**Comment by shibayan** [comment]
I just now performed a new deployment against `westus2` from the actual Deploy to Azure button and could not reproduce it.

Please change the region or give it some time and try again.

**Comment by desmphil** [comment]
After reviewing my template it seems it doesn't like any (hyphen) in the prefix

**Comment by desmphil** [comment]
Yes, however the naming of the object really isn't much customizable thats my only problem.
I will have to alter the template of object creation.

Thank you
