### ISSUE TITLE
Configure Durable Functions Hub

### ISSUE THREAD

**Issue by johnrom** [shibayan/keyvault-acmebot#457]
I have multiple environments with separate SSL concerns. I attempted to deploy two instances of this app, but this will not work if they use the same storage account. Queueing an orchestration on one Function will trigger execution on another function, etc. I'm wondering if there's any way to configure the Durable Functions Hub to support using two instances.

An example to make this dynamic would be to modify the `hubName` to support variable replacement via appsettings.json, like this:

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs?tabs=csharp#hostjson-functions-20-1

This would be a breaking change that would require adding the `hubName` to appsettings / app service configuration.

**Comment by shibayan** [comment]
One Acmebot per Azure AD tenant is sufficient in most cases. Please understand this first.

Azure Functions does not recommend sharing back-end storage accounts, so it is recommended that they be created separately.

If you must change the `HubName`, you can do so by adding `AzureFunctionsJobHost__extensions__durableTask__hubName` to App Settings. https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#override-hostjson-values

**Comment by johnrom** [comment]
Ah! That makes sense. I missed that part of the override documentation.

We have many different services on a single tenant, and I hesitate to give the resource group scope of one endpoint permission to modify the key vault certificates for another scope (staging, production, multiple websites), especially since those have different scopes and authentication in the upstream DNS provider.

I think it's probably best to isolate storage accounts as well, but the App Settings override will be enough for now.
