### ISSUE TITLE
PEM certificate extracted from PFX is in the wrong order

### ISSUE THREAD

**Issue by m4r1u2** [shibayan/keyvault-acmebot#458]
**Describe the bug**
PEM certificate extracted from PFX is in the wrong order.
The PEM file had the structure of:

PRIVATE KEY
ROOT
INTERMEDIATE
SERVER

Expected:
SERVER
INTERMEDIATE
ROOT
KEY

This is the same issue opened for [secrets-store-csi-driver-provider-azure](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/156) for k8s.

I find this comment interesting: 
https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/156#issuecomment-658466219_
> Had a discussion with @pwiens offline. The Azure Key Vault Provider returns the certs in the order in which they were uploaded. Unfortunately, in their scenario, they don't have control over the order of the certificates before upload.

Is acmebot validating chain order?

**To Reproduce**
1. Renew/Add Cert via Dashboard (DNS challange)
2. Download PFX from KeyVault
3. Verify order with OpenSSL tool

**Environment (please complete the following information):**
 - Certificate Type: Wildcard
 - Certificate Deploy Target: Application Gateway

**Additional context**

By using a AcmeBot generated certificate in KeyVault with a ApplicationGatewayV2 we get this certificate chain:
```
---
Certificate chain
 0 s:/CN=*.testdomain.com
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
 2 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
---
```
This is wrong! 

We see the same when we download the PFX and extracts the cacerts:
```
openssl pkcs12 -in kv-acmebot-testdomain-20220317.pfx -cacerts -nokeys -chain  -passin pass:
MAC verified OK
Bag Attributes: <Empty Attributes>
subject=/C=US/O=Internet Security Research Group/CN=ISRG Root X1
issuer=/O=Digital Signature Trust Co./CN=DST Root CA X3
-----BEGIN CERTIFICATE-----
MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
..
Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
-----END CERTIFICATE-----
Bag Attributes: <Empty Attributes>
subject=/C=US/O=Let's Encrypt/CN=R3
issuer=/C=US/O=Internet Security Research Group/CN=ISRG Root X1
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
..
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
```

**Comment by shibayan** [comment]
This problem is caused by the strange behavior of Key Vault. Acmebot is creating the correct certificate chain, but the order changes when downloading from Key Vault.

For more information, see the discussion below. #406

**Comment by m4r1u2** [comment]
Thanks for the referance @shibayan 
This fix my issue.
> If you set Acmebot:MitigateChainOrder to true, you can avoid incorrect order in the Application Gateway.

I must have overlooked this in the wiki documentation. 
Any reason why this shouldnt be default set true?

**Comment by shibayan** [comment]
The reason it cannot be true by default is compatibility with previous versions and the fact that this certificate chain ordering problem generally occurs only in Application Gateway.

In the past, when it was enabled by default, compatibility was affected, so it was made configurable.
