### ISSUE TITLE
Set expiration date when creating certificate

### ISSUE THREAD

**Issue by madsd** [shibayan/keyvault-acmebot#459]
**Is your feature request related to a problem? Please describe.**
I sometimes need to test what happens when a certificate expires, so it would be nice to be able to generate a certificate that expires in 1 day or 2 days.

**Describe the solution you'd like**
A setting in the advanced options to define expiry date.

**Comment by shibayan** [comment]
There are currently no plans to make it possible to specify an expiration date.

The `Acmebot:RenewBeforeExpiry` option is available if you want to check the behavior when auto-renewing. If you want to test with invalid certificates, it is recommended to use the Let's Encrypt staging endpoint.

**Comment by madsd** [comment]
Hi @shibayan thank you for responding to my question. I am not looking to test renewal or have invalid certificates. I am looking for valid certificates with a short expiration. Can you point me to where in your code you are configuring the certificate options. I am happy to work on a PR to add this functionality.

**Comment by shibayan** [comment]
This application is not intended to issue test certificates. It's main purpose is to provide continuous and stable certificate renewal in a production environment.

Therefore, the ability to issue certificates with short validity periods will not be implemented. There are many alternatives for testing purposes.
