### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by prabhakarreddy1234** [shibayan/keyvault-acmebot#46]
I followed your instructions. When i try to login i get below error.

> 
AADSTS650052: The app needs access to a service (\"http://rts.powerapps.com\") that your organization 

Did i miss anything?

**Comment by prabhakarreddy1234** [comment]
I found the answer. I had to remove `Power apps`  API Permission explicitly from AD App Registrations and granted admin consent.

**Comment by MaxiPigna** [comment]
How did you solve it? I added this API permission to che Client App Registration, but it didn't work.
![image](https://user-images.githubusercontent.com/33937977/91752589-d9e5f600-ebc6-11ea-970b-2b24e928a3db.png)
