### ISSUE TITLE
Add stateless, programmatic creation of SSL certificates

### ISSUE THREAD

**Issue by byteknacker** [shibayan/keyvault-acmebot#464]
**This is a feature request**

So far, I have enjoyed using your application to create SSL certificates. But I can only do so manually by accessing the dashboard endpoint. I propose that there is a way to use CLI to manipulate ACME Bot such that one can create a certificate, e.g. in Bash.

**Describe the solution you'd like**

Whenever I deploy a new app to my Azure infrastructure, I need to determine the subdomain name and then go to the ACME Bot dashboard to manually enter the domain name and click on the + button to create a certificate. Even though the rest of the process is already automated, this one manual step hinders me from implementing the ACME bot in a CI/CD pipeline. 

I have a Gitlab CI/CD pipeline that deploys the Azure infrastructure and another one that deploys my app to this infrastructure. I wish to be able to write a Gitlab job that uses Bash to talk to an API of ACME Bot. I will have flags and options in this command to let the ACME bot know what certificate to create. When I run this command, the ACME bot creates the certificate as if I did it in the web interface. My Gitlab pipeline can then redeploy the new infra with the added certificate and let Application Gateway pick up the new one and use it for the new hostname for routing. 

Example of a CLI command:

acmebot apply --dns-zone "subdomain.example.com" --dns-name "name" (optional flags for advanced settings...)

Note that "apply" is used instead of "create" to make this idempotent. ACME bot only creates a new certificate if it did not exist before.

I can then set the value of --dns-zone and --dns-name to a variable that I can retrieve from my app configuration at runtime. This then creates the certificate automatically without me logging into the Dashboard. 

A developer without any knowledge of SSL/infra/Azure etc., will be able to deploy an HTTPS based app at a click of a button. 

If this is not implemented, either we have to interrupt the Gitlab pipeline or use Selenium or some crawlers to crawl through the Dashboard. This is cumbersome and hard to maintain with every upgrade and breaking changes to the ACME bot. 

I propose to develop an ACME Bot API with endpoints and a CLI toolkit. You do not need a lot of commands since ACME Bot does only one thing: create the certificate. 

**Additional context**
This step is crucial to increasing this repository's adoption since programmatic access is an essential feature for enterprises and startups alike.

**Comment by shibayan** [comment]
I do not see the need to implement a dedicated CLI, but the equivalent can be accomplished from a publicly available REST API. Some users are already using the REST API to programmatically issue certificates.

https://github.com/shibayan/keyvault-acmebot/wiki/REST-API

**Comment by byteknacker** [comment]
Ok this works as well. Cheers!
