### ISSUE TITLE
NullReferenceException thrown instead of useful error when ACME new-order rate limit is hit

### ISSUE THREAD

**Issue by gberesford** [shibayan/keyvault-acmebot#466]
When the letencrypt new-order endpoint starts ratelimiting and returning HTTP status code 429, the ACMESharp.Protocol.AcmeProtocolClient.SendAcmeAsync method starts throwing NullReferenceExceptions.

https://github.com/shibayan/ACMESharpCore/blob/6c0d3c7836bc8d697dc00fb7a470b9fdcfb86008/src/ACMESharp/Protocol/AcmeProtocolClient.cs#L801
This happens because this if statement is always true (when hitting the rate-limit), so the `continue` on line 805 is always executed. This means that the assignment to `ex` on line 808 is never executed, so when `ex` is thrown on line 826, it is still `null` and C# throws a NullReferenceException instead.

It would be better if this method threw an AcmeProtocolException with the details filled in from the HTTP response - it would mean that the user could see that their request failed due to the rate-limit, otherwise you end up with errors like this discussion: https://github.com/shibayan/keyvault-acmebot/discussions/424

**Comment by shibayan** [comment]
Thanks, I have improved the handling of HTTP 429.
