### ISSUE TITLE
Azure function app setting names can only contain letters, numbers (0-9), periods ("."), and underscores ("_")

### ISSUE THREAD

**Issue by Dolphinsimon** [shibayan/keyvault-acmebot#471]
I have used the project for months and it works great. 
But seems that Azure function has changed the app settings policy.
When I try to set the 'Acmebot:VaultBaseUrl' in Azure function app settings, an error occurred as 'App setting names can only contain letters, numbers (0-9), periods ("."), and underscores ("_")'
![2022-04-06 164358](https://user-images.githubusercontent.com/4425053/161934522-85173dda-fbd5-4bda-bd46-66e86e2990e4.png)

**Comment by shibayan** [comment]
I could not reproduce this problem in my environment. I consider this to be a bug in Azure Portal because the documentation and the actual behavior are different.
https://docs.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#configure-app-settings

**Comment by Dolphinsimon** [comment]
You can try create a FunctionApp in Linux App Service Plan. I can confirm the FunctionApp in Windows is working properly.

**Comment by sven5** [comment]
I can confirm this to be an issue with Linux App Service Plan.

**Comment by shibayan** [comment]
As you can see from the officially provided ARM Template and Terraform Module, running on Linux Azure Functions is not officially supported.

I have not confirmed that it works with Azure Functions on Linux, and there is no advantage to using Acmebot with the Linux Consumption plan, so it will not be supported.

**Comment by sven5** [comment]
This is really a limitation for which I can't see real reasons.
Our background is that we're already running some web and function apps on a Linux app service plan. So why deploy a new asp? 

However, I think the modifications would be small to get it working.

**Comment by Dolphinsimon** [comment]
@sven5 I agree with you.

**Comment by Dolphinsimon** [comment]
@sven5 It works like a charm. Thanks for your help!
