### ISSUE TITLE
Error Singleton lock renewal failed 

### ISSUE THREAD

**Issue by sven5** [shibayan/keyvault-acmebot#472]
I'm getting the following error in the log:

`[Error] Singleton lock renewal failed for blob 'functions-acmebot/host' with error code 409: LeaseIdMismatchWithLeaseOperation. The last successful renewal completed at 2022-04-07T06:38:40.929Z (112700 milliseconds ago) with a duration of 5 milliseconds. The lease period was 15000 milliseconds.`

**Comment by shibayan** [comment]
This is an error log produced by Azure Functions, which has nothing to do with Acmebot.
