### ISSUE TITLE
GratisDNS became one.com, so the certificate issueing is not working anymore

### ISSUE THREAD

**Issue by cristian-smarttid** [shibayan/keyvault-acmebot#478]
Hello!

GratisDNS became one.com, so the certificate issueing stopped working, because they started to port everyone to one.com.
Can we please have an api implementation for one.com?

Thank you!

**Comment by shibayan** [comment]
The GratisDNS Provider is unmaintained and will be removed in Acmebot v4. Contributions are always welcome.
