### ISSUE TITLE
Create unit tests for providers

### ISSUE THREAD

**Issue by eloekset** [shibayan/keyvault-acmebot#493]
**Is your feature request related to a problem? Please describe.**
In #492 I suspected a bug in the implementation of `DeleteTxtRecordAsync` for the `DomeneShopProvider`. 

**Describe the solution you'd like**
To verify the bug existed and was fixed, I created a unit test project and implemented tests for all the public methods of `DomeneShopProvider`. Consider implementing tests for the other existing providers to verify the functionality and better describe the provider for developers without access to that provider's API.

**Describe alternatives you've considered**
- Implement changes and deploy a pre-release to test and verify functionality live against the provider's API.
- Create another test project for integration tests with sample data that verifies functionality all the way from the AcmeBot for each provider. This requires a configuration with credentials that should be gitignored and the tests must be easily modified with sample data that suits a developers own domain.

**Additional context**
The tests I've implemented will be sent in a separate PR.
![image](https://user-images.githubusercontent.com/791721/177057328-ff3ecdad-4808-4177-9240-8d16cd097d05.png)

**Comment by shibayan** [comment]
I do not plan to support this because we do not see the value in unit tests that do not access the actual DNS Provider API. Mock APIs can verify reads, but cannot verify that Create / Update requests are correct.

It is possible to create a test that runs the DNS Provider's API, but this is not practical due to the additional cost involved.

**Comment by eloekset** [comment]
Ok, I'll keep this feature branch hanging around: https://github.com/eloekset/keyvault-acmebot/tree/feature/DomeneShopUnitTests 
If anyone else is interested in unit tests at great help developing additional providers, feel free to pull for this branch. I'll use it when implementing a provider for Namecheap soon.
