### ISSUE TITLE
Orchestrator function 'IssueCertificate' failed: The activity function 'Order' failed: "missing next nonce needed to sign request payload". See the function execution logs for additional details.

### ISSUE THREAD

**Issue by wasker** [shibayan/keyvault-acmebot#515]
**Describe the bug**

I'm unable to issue a new certificate due to the "Orchestrator function 'IssueCertificate' failed: The activity function 'Order' failed: "missing next nonce needed to sign request payload". See the function execution logs for additional details." error.

**To Reproduce**

1. Go to Dashboard
2. Click on Add
3. Fill out new cert details

**Environment (please complete the following information):**
 - Certificate Type: Zone apex
 - Certificate Deploy Target: KeyVault

**Additional context**

Similar to #352, but I'm using v4.9.0.18814 and it's a new cert issue, not renewal.

**Comment by shibayan** [comment]
Error logs collected by Application Insights are required to identify the problem. Please share the logs of the relevant errors.

**Comment by wasker** [comment]
@shibayan Which table should I look into?

**Comment by shibayan** [comment]
See this article.
https://docs.microsoft.com/en-us/azure/azure-functions/analyze-telemetry-data
