### ISSUE TITLE
App Role for revocation

### ISSUE THREAD

**Issue by hbuckle** [shibayan/keyvault-acmebot#531]
Would it be possible to add an app role for certificate revocation? We would like to allow anyone to issue certificates but restrict revocation to only certain people.

**Comment by shibayan** [comment]
I thought this would be a good time to include a breaking change. Specifically, the App Role will be split into the following two parts.

- `Acmebot.IssueCertificate`
- `Acmebot.RevokeCertificate`

**Comment by hbuckle** [comment]
> I thought this would be a good time to include a breaking change. Specifically, the App Role will be split into the following two parts.
> 
>     * `Acmebot.IssueCertificate`
> 
>     * `Acmebot.RevokeCertificate`

That would be great!
