### ISSUE TITLE
Azure.Identity v1.8 causes an exception on Azure Government instance

### ISSUE THREAD

**Issue by bsuchorowski** [shibayan/keyvault-acmebot#545]
Hello,

Our Azure Gov instance of keyvault-acmebot started throwing and exception.

![image](https://user-images.githubusercontent.com/20202156/207837676-f4828fab-034b-4a1f-9ca7-bf7a3cce4d2c.png)

This is exactly the same error as somebody reported for Azure.Identity nuget package:
https://github.com/Azure/azure-sdk-for-net/issues/32498

As you have recently updated Azure.Identity package then I revereted back my Function App to v4.0.2  (which uses older Azure.Identity v1.7.0) and everything works fine on this version.

It seems that MS is going to fix that issue in currently unreleased v1.9.0

Please consider:
1. Reverting back dependency of Azure.Identity to 1.7.0 until 1.9.0 is released
2. Finding any other workaround for 1.8.0

Until this one is fixed we are stuck with version v4.0.2

**Comment by shibayan** [comment]
Thanks for the report. I can't confirm that it works with US Gov Cloud, so your report is very important and appreciated.

Basically, I would like to wait for the release of v1.9.0, but will consider reverting to v1.7.0 if we determine that the update will take too long.

**Comment by bsuchorowski** [comment]
Sure. 1.9.0 seems to be just around the corner. We will stay at 4.0.2 until a new version, based on Azure.Identity 1.9.0, is released. I will be able to confirm the status afterwards.

**Comment by willdovetx** [comment]
is there anything we can change in the template to force 4.0.2 and v1.7.0 use?

**Comment by shibayan** [comment]
@willdovetx Change `latest.zip` to `4.0.2.zip` in the URL set in `WEBSITE_RUN_FROM_PACKAGE`. If you have already deployed it, you can change it from Configuration in Azure Portal.

**Comment by bsuchorowski** [comment]
Exactly, it has not been documented anywhere as far as I know but we figured it out.

**Comment by willdovetx** [comment]
> @willdovetx Change `latest.zip` to `4.0.2.zip` in the URL set in `WEBSITE_RUN_FROM_PACKAGE`. If you have already deployed it, you can change it from Configuration in Azure Portal.

Thank you, this fixed my issue.

**Comment by Dolphinsimon** [comment]
I can confirm the same exception throws in AzureChina environment.

**Comment by Dolphinsimon** [comment]
@shibayan I have tested with the latest master branch after the nuget package updated to v1.8.1. The same exception throws out:
![SCR-20230114-ipo](https://user-images.githubusercontent.com/4425053/212457684-2fbb9b82-3242-4955-945a-588120e34d80.png)
And this is the deployment logs, the latest commit id in master branch.
![SCR-20230114-iys](https://user-images.githubusercontent.com/4425053/212457762-96c263dc-53c8-4032-91e1-9c52aeea783a.png)

**Comment by shibayan** [comment]
It seems that the fix is not complete in Azure.Identity v1.8.1. It will be necessary to create an Issue to the Azure SDK repository.

**Comment by Dolphinsimon** [comment]
Azure.Identity v1.8.2 has been [released](https://github.com/Azure/azure-sdk-for-net/releases/tag/Azure.Identity_1.8.2).
