### ISSUE TITLE
fix (?) DNS Zone Name vs DNS Domain Name 

### ISSUE THREAD

**Issue by datocrats-org** [shibayan/keyvault-acmebot#55]
The example shows daruyanagi.com in the dropdown.  Is that the name of the DNS Zone in your Azure?  Do we have to make a DNS Zone with the same name as our root domain for it to work?  I noticed I set up my DNS zone with a different name, will that info in the UI get carried through in the function to the request to Let's Encrypt?  Or do you query the CNAME records stored in the DNS Zone itself?

**Comment by shibayan** [comment]
The dropdown list shows the list of Zones in Azure DNS. The domain names added in the UI is passed to Let's Encrypt.
