### ISSUE TITLE
Failed : GetAllCertificates

### ISSUE THREAD

**Issue by ash06dec** [shibayan/keyvault-acmebot#557]
Orchestrator function 'GetCertificates_Orchestrator' failed: The activity function 'GetAllCertificates' failed: "Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (An attempt was made to access a socket in a way forbidden by its access permissions. (asrwe-lowcode-s-kvt-sbx.vault.azure.net:443)) (An attempt was made to access a socket in a way forbidden by its access permissions. (asrwe-lowcode-s-kvt-sbx.vault.azure.net:443)) (An attempt was made to access a socket in a way forbidden by its access permissions. (asrwe-lowcode-s-kvt-sbx.vault.azure.net:443)) (An attempt was made to access a socket in a way forbidden by its access permissions. (asrwe-lowcode-s-kvt-sbx.vault.azure.net:443))". See the function execution logs for additional details.

![image](https://user-images.githubusercontent.com/17750641/216982000-403c30b7-3886-472f-b96d-49c433839807.png)

FYI,

Function app has all permission on the given KV.
Re-deployed couple of times.

Its been working in others env flawlessly but new deployment shows error. Any idea ?

**Comment by shibayan** [comment]
It looks like the problem is on the App Service platform side, as it appears to be an error around sockets.

Acmebot only uses the Key Vault SDK, so it is not directly involved with sockets.
