### ISSUE TITLE
upstream dependency issue

### ISSUE THREAD

**Issue by datocrats-org** [shibayan/keyvault-acmebot#56]
When trying to clone and debug on vscode I get a dependency error that I think could be resolved if I manually installed the dependency (but I don't know how to do that in .NET).

$ dotnet restore
C:\code\keyvault-acmebot\KeyVault.Acmebot\KeyVault.Acmebot.csproj : warning NU1603: KeyVault.Acmebot depends on Microsoft.Azure.WebJobs.Host.Storage (>= 3.0.11) but Microsoft.Azure.WebJobs.Host.Storage 3.0.11 was not found. An approximate best match of Microsoft.Azure.WebJobs.Host.Storage 3.0.13 was resolved. [C:\code\keyvault-acmebot\KeyVault.Acmebot.sln]

Similar issue: https://github.com/Azure/azure-webjobs-sdk-extensions/issues/607

**Comment by shibayan** [comment]
This is a problem with Azure Function SDK
