### ISSUE TITLE
AppGateway_v1 secret format support

### ISSUE THREAD

**Issue by aczepiec** [shibayan/keyvault-acmebot#561]
Hi, 

There is no way to create a reference to generated certificates when using AppGateway Standard or WAF SKU. AppGateway Standard and WAF SKU expects certificates to be in base64 format and stored in keyvault as "secret" instead of "certificate".

```
# az network application-gateway ssl-cert create -n test_cert --gateway-name sample-gateway --resource-group sample-rg --key-vault-secret-id <certificate reference>

Message: SKU Tiers 'Standard_v2, WAF_v2' support KeyVaultSecretId while SKU Tiers 'Standard, WAF' support Data in Certificate [...]
Code: ApplicationGatewayCertificatePropertyInvalidForSku
```

The proposition is to add function to convert generated certificate and store it as a secret instead of certificate as Application Gateway v1 does not support SSL certificates stored in Azure Key Vault. 

Regards
AC

**Comment by shibayan** [comment]
Acmebot's role is to issue and renew certificates integrated with the Key Vault, so it is basically not involved in the services that use those certificates.

For older services like App Gateway v1 that do not allow Key Vault references, each user must write code to integrate them.
