### ISSUE TITLE
GetDnsZones type cast issue

### ISSUE THREAD

**Issue by datocrats-org** [shibayan/keyvault-acmebot#57]
I don't know how to troubleshoot this.  I think it's a type mismatch that should not be affected by what I have in my DNS name.  Below is the log of the error in function app integrate run.

Executing 'GetDnsZones' (Reason='This function was programmatically called via the host APIs.', Id=9d72e3e9-5ae3-432c-b7cf-44ce42bd188f)
2019-12-30T00:51:35.662 [Error] Executed 'GetDnsZones' (Failed, Id=9d72e3e9-5ae3-432c-b7cf-44ce42bd188f)
Unable to cast object of type 'System.String' to type 'Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext'.

**Comment by shibayan** [comment]
Do not execute the function from the Azure portal. It is not such a design.
