### ISSUE TITLE
Cannot Create Certificates for Selected Azure DNS Zone

### ISSUE THREAD

**Issue by A-Thomas-91** [shibayan/keyvault-acmebot#583]
I have a domain which there has been 2 Azure DNS zones configured (both public). The one I am selecting to use for certificate deployment is one which the nameservers resolve to NSX-08 servers instead of NSX-01. The first zone was created was testing purposes previously.
However when attempting to use this zone it throws a PreconditionException as the NSX-01 name servers are expected.

**To Reproduce**
Create a duplicate Azure DNS Zone and select it from the GUI when making a certificate.

I know the ACME challenges won't complete as there would be records for a zone which wouldn't resolve.

**Comment by shibayan** [comment]
Does this mean there is an Azure DNS Zone with the same name?

**Comment by shibayan** [comment]
Since Acmebot uses domain name matching to find DNS Zones, it will not work correctly if the same DNS Zone exists. This affects the behavior of certificate renewal, since it is impossible to switch to a unique ID, such as a resource ID.
