### ISSUE TITLE
The Azure Function is dependent on shibayan.blob.core.windows..../index.html

### ISSUE THREAD

**Issue by abergs** [shibayan/keyvault-acmebot#59]
While it's "running as a package" the proxy for "add-certificate" has the backend url of your blob storage. Is this by design? Is it possible to make it run locally on the function instead so that it does not cause costs for you or outage if you ever remove/change that file?

![image](https://user-images.githubusercontent.com/357283/71724817-ff511300-2e31-11ea-809b-3a8883243f9f.png)

**Comment by shibayan** [comment]
It is by design. Required for providing Web UI.

This function doesn't consider to be executed locally at all.  It might be possible if you are Azure professional, but I do not intend to support it.

**Comment by abergs** [comment]
I understand.

I think it could be possible either host that index.html in the storage account created during setup. Or return it from an azure function, e.g. https://www.vainolo.com/2018/03/17/azure-functions-part-2-serving-html-pages-with-azure-functions/

Making the service/function self contained would make it more reliable in the long term.

**Comment by shibayan** [comment]
The Web UI is hosted on my account because the application and deployment cycle are different.

It may be included in the application package in the future, but I have no plans at this time.
