### ISSUE TITLE
Support for HTTP challenge type using Azure Storage Account

### ISSUE THREAD

**Issue by ckupferschmid** [shibayan/keyvault-acmebot#606]
**Is your feature request related to a problem? Please describe.**
We are using several domain providers that are not listed to be supported.

**Describe the solution you'd like**
It would be nice to have the possibility to use Azure Storage Account to store the file with the challenge token. That would allow using this solution for almost any setup and independent of DNS service providers.
We are aware, that this setup would require e.g. an Application Gateway or FrontDoor or anything else that would terminate the challenge request and route the request to the storage account and folder.  

**Describe alternatives you've considered**
Other solutions that would allow that, do not support Azure Key Vault to store and manage the certificates.

**Additional context**

**Comment by shibayan** [comment]
Duplicated #197
