### ISSUE TITLE
Failed automatic certificate renew

### ISSUE THREAD

**Issue by ash06dec** [shibayan/keyvault-acmebot#607]
Dashboard is not able to renew the certificate automatically. 

Attaching the SS

1) The number of day set as 30 for auto renew in the function app
![image](https://github.com/shibayan/keyvault-acmebot/assets/17750641/792c8817-49a3-4211-a894-8c99e974db65)

2) By doing hard renew, gets the below error
![image](https://github.com/shibayan/keyvault-acmebot/assets/17750641/11c47182-7991-4d74-a1a7-7f518bc045d8)

**Comment by shibayan** [comment]
Verify that a TXT record named `_acme-challenge` has been created for the appropriate DNS Zone. If so, check to see if you can retrieve the value of the TXT record using nslookup or similar.

**Comment by ash06dec** [comment]
It cant find the domain 
![image](https://github.com/shibayan/keyvault-acmebot/assets/17750641/955b09a3-b59b-4c07-ad62-2869351e9edf)

**Comment by ash06dec** [comment]
> Verify that a TXT record named `_acme-challenge` has been created for the appropriate DNS Zone. If so, check to see if you can retrieve the value of the TXT record using nslookup or similar.

yeah there is only one domain. So the record is created in correct domain. 

- nslookup _acme-challenge : Non existent
- nslookup _acme-challenge.mijn-o.asrvermogensbeheer.azure.asr.nl : Non existent
- nslookup mijn-o.asrvermogensbeheer.azure.asr.nl : Resolve to correct server
