### ISSUE TITLE
certificate validity

### ISSUE THREAD

**Issue by ruchi1803** [shibayan/keyvault-acmebot#652]
**Is your feature request related to a problem? Please describe.**
Existing application renew the certificate for 90 days.

**Describe the solution you'd like**
Since we are using entrust which support 1 year validity for certificate, we would like to know where I can make necessary changes for this custom solution.

**Comment by shibayan** [comment]
The expiration date of the certificate depends on the CA. Customization is not possible.

**Comment by treidel** [comment]
HI @shibayan,  I thought I'd mention here that ACMEv2 does have support for a client to request a specific expiry date from a CA via the 'notAfter' field in the Order object.  The CA isn't obligated to honor the value requested (and many/most will ignore this field) but for those CAs that do allow end users to request specific expiry dates this field achieves what @ruchi1803 was looking for.
