### ISSUE TITLE
Would it be nice to update DNS requirements in the Readme?

### ISSUE THREAD

**Issue by letrape** [shibayan/keyvault-acmebot#66]
I'm new to certificate management in azure and I've tried all the morning to setup certificates facing the issue:

"Orchestrator function 'IssueCertificate' failed: The activity function 'CheckDnsChallenge' 

It would be nice if the Readme includes that in order to issue a certificate via this tool you need to have full control of the DNS Zone, that means you need to do DNS delegation.

I've been using the GoDaddy default DNS managment and worked great until I've tried to use this tool. 

Is that correct? In order to setup this tool properly is important to have a DNS Zone configured and delegated from others DNS ?

**Comment by shibayan** [comment]
It clearly states that Azure DNS is required and that DNS zone delegation is required.

I'm not considering supporting other providers than Azure DNS.
