### ISSUE TITLE
Missing user-agent header in Acme Requests? (BuyPass Acme API)

### ISSUE THREAD

**Issue by FredrikMelby** [shibayan/keyvault-acmebot#678]
**Describe the bug**
We are receiving http400 errors from BuyPass Acme API when we try to renew or create new certificates. I have been in contact with their support, and they have made a change to their Acme API being more strict with the user-agent header:
![image](https://github.com/shibayan/keyvault-acmebot/assets/29274188/a63e3f42-d668-41db-8421-5f438903ba71)
(https://community.buypass.com/t/p8y833j/get-http-bad-request-from-acme-api#x2y881l)

"ACME clients MUST send a User-Agent header field, in accordance with
   [[RFC7231](https://datatracker.ietf.org/doc/html/rfc7231)].  This header field SHOULD include the name and version of
   the ACME software in addition to the name and version of the
   underlying HTTP client software."

Is this maybe the case here?

BuyPass API: https://api.buypass.com/acme/directory 

See #671 for related information.

**Comment by shibayan** [comment]
Thanks for the report. I was able to confirm that the certificate fails to issue with BuyPass in my environment as well, so I added the User-Agent so that it works correctly.

A fixed version will be released shortly.
