### ISSUE TITLE
How to revoke / delete a wrong certificate

### ISSUE THREAD

**Issue by pstlaurent-biron** [shibayan/keyvault-acmebot#69]
Hello,

There is a way to delete / revoke a wrong certificate and recreate it?

I deleted it from the KeyVault and now it's impossible to recreate a new certificate with the right information.

`Orchestrator function 'IssueCertificate' failed: The activity function 'FinalizeOrder' failed: "Failed to deserialize exception from TaskActivity: {"$type":"ACMESharp.Protocol.AcmeProtocolException, ACMESharp","ProblemType":19,"ProblemTypeRaw":"urn:ietf:params:acme:error:unauthorized","ProblemDetail":"Error finalizing order :: Order includes different number of names than CSR specifies","ProblemStatus":403,"StackTrace":"   at ACMESharp.Protocol.AcmeProtocolClient.SendAcmeAsync(Uri uri, HttpMethod method, Object message, HttpStatusCode[] expectedStatuses, Boolean skipNonce, Boolean skipSigning, Boolean includePublicKey, CancellationToken cancel, String opName)`

Thanks

**Comment by shibayan** [comment]
I think that there is a pending certificate in Key Vault. Please try to delete the certificate in the pending state from Key Vault by referring to the following document.

https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate/pending?view=azure-cli-latest

**Comment by pstlaurent-biron** [comment]
Excellent, it works. The pending certificate has been deleted.

Thanks again!

**Comment by JohnLBevan** [comment]
I had the same issue, but couldn't follow the given advice as my key vault has purge protection enabled (so would have required waiting 90 days for the protection period to expire, or reaching out to MS Support).  
My workaround was to undelete the certificate

```
$myVaultName = 'name of your key vault'

# list deleted certs in the vault
Get-AzKeyVaultCertificate -VaultName $myVaultName -InRemovedState

# undelete your cert
$myCertName = 'enter the name of the cert you want to recover'
Undo-AzKeyVaultCertificateRemoval -VaultName $myVaultName -Name $myCertName
```

Once undeleted I could amend the issuance policy (e.g. via the Azure Portal UI) to change the definition of the cert as required, then through the AcmeBot Dashboard ran a renew to issue a new version with the new definition (per https://github.com/shibayan/keyvault-acmebot/issues/705#issuecomment-2096298673).

Hope the above undelete workaround helps others who've gone down the wrong route and found themselves stuck as I had.
