### ISSUE TITLE
Current limitations in Entrust section in EAB Wiki page should be removed 

### ISSUE THREAD

**Issue by treidel** [shibayan/keyvault-acmebot#693]
The Entrust ACME service now supports the mandatory/default ES256 hash algorithm.   The "Current limitations in Entrust" section can be removed as it is no longer required to override the hash algorithm to use RSA signatures instead, e.g. the default settings for acmebot are sufficient to connect to successfully issue certificates via Entrust. 

https://github.com/shibayan/keyvault-acmebot/wiki/External-Account-Binding

**Comment by shibayan** [comment]
Is there any official information that it has been supported?

**Comment by shibayan** [comment]
Thanks for the information. I am relieved to know that the information is reliable.

As for the Wiki, it has been fixed.
