### ISSUE TITLE
Dashboard DNS Zones Sort Order

### ISSUE THREAD

**Issue by JohnLBevan** [shibayan/keyvault-acmebot#734]
**Is your feature request related to a problem? Please describe.**

Currently when adding a new certificate via the dashboard the zones are ordered by provider; but zones within a provider are shown in an arbitrary order (i.e. whatever order they were returned in by the provider).  Where you have many zones under a single provider this can make finding the zone you're after more time consuming that it needs to be.

**Describe the solution you'd like**

Order zones first by their provider (as is the case today), then by the zone/domain name, so one can quickly find the zone of interest.

**Describe alternatives you've considered**

Alternative solutions could be to sort all zones by name regardless of provider (as most of the time you'll only care about the zone / not where that zone is hosted, and you're unlikely to have the same zone in multiple providers as only one can be active from a public DNS perspective) would also work; though that changes the existing behaviour rather than enhancing what's already there.

Another option could be to allow grouping by apex domain, so if  you have different zones for `prod.example.com` vs `test.example.com` you'd have both listed together as both are part of `example.com`; though this would require ignoring TLDs  as sorting by `.co.uk` vs `.com` would likely be unintuitive; and tbh feels over complicated.

So the proposed solution feels like the simplest implementation that would add greatest value.

**Comment by shibayan** [comment]
The DNS zone list display will soon be changed to the following, making it easier to understand. It will be easier to understand because it will be sorted within the provider.

![image](https://github.com/user-attachments/assets/20dbf7f2-ddc3-4bc8-93bb-88b626293a7d)

**Comment by JohnLBevan** [comment]
Fantastic - thank-you :)
