### ISSUE TITLE
support user managed identity

### ISSUE THREAD

**Issue by baoj-dfo** [shibayan/keyvault-acmebot#745]
**Is your feature request related to a problem? Please describe.**
Current solution only support "system managed identity", but not support "user managed identity"

**Describe the solution you'd like**
We expect it support "user managed identity"

**Describe alternatives you've considered**

**Additional context**
"user managed identity" will be more flexible on the RBAC config of Azure DNS or Keyvault.

**Comment by shibayan** [comment]
For applications that require completely independent permissions, such as Acmebot, there doesn't seem to be any benefit to sharing permissions using User Assigned Managed Identity.

If you have a more specific use case, please let us know. We will consider it based on the details.

**Comment by shibayan** [comment]
Unless you can tell us how it would be useful and what System Assigned Managed Identity lacks, we cannot consider it.

In my opinion, System Assigned Managed Identity is the best choice because I believe Acmebot should assign unique permissions.
