### ISSUE TITLE
Support for other DNS providers

### ISSUE THREAD

**Issue by shibayan** [shibayan/keyvault-acmebot#76]
- [x] Introduce DNS provider model (#93)
- [x] Refine configuration (#130)

### Providers

- [x] Azure DNS (Default)
- [x] Cloudflare (#131)
- [x] GratisDNS (#129)

Ref #68

**Comment by ltctech** [comment]
Any chance you could also support Route53?

Route53 has been around much longer than Azure DNS, hence our DNS is with Route53 but our sites with Azure.

**Comment by shibayan** [comment]
Since Cloudflare's API does not meet the required behavior, I would consider supporting a different DNS provider.

List common DNS services other than Azure DNS, if any.

**Comment by shibayan** [comment]
Azure DNS / Cloudflare / GratisDNS

These three providers will be released. More may be added in the future.

**Comment by timhowardedx** [comment]
This is very exciting.  I would really like support for Dreamhost, which is already supported in acme.sh (see [here](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_dreamhost.sh)) and Posh-ACME.  Is there a way that I could help out with that?

**Comment by GeorgDangl** [comment]
Yes, this is really exciting!
Do you have any idea when this will be available?

**Comment by shibayan** [comment]
Support for Cloudflare is highly requested and I hope to release it soon in the next version.
