### ISSUE TITLE
Add support for Flex Consumption plans

### ISSUE THREAD

**Issue by jamesharling** [shibayan/keyvault-acmebot#764]
**Is your feature request related to a problem? Please describe.**
Currently this deployment only uses the regular consumption plan for its App Service Plan - this older plan does not support any advanced networking integrations. By moving to, or optionally supporting, Flex Consumption plans it would be possible for all of the resources to require private endpoint access - ideal for something as sensitive as certificate management.

**Describe the solution you'd like**
The deployment template migrates to using flex consumption plans, or has an option to opt in to them (as they are preview only at the moment). Additional configuration should be exposed to create private endpoints and/or network injection. 

**Describe alternatives you've considered**
None that apply.

**Additional context**
n/a

**Comment by shibayan** [comment]
Duplicate #624
