### ISSUE TITLE
Refine documentation

### ISSUE THREAD

**Issue by shibayan** [shibayan/keyvault-acmebot#77]

**Comment by jurajsucik** [comment]
hey @shibayan, I could help with the documentation. Could you give me some more details what you would need?

**Comment by shibayan** [comment]
Thank you very much. I'm not good at English, so the README may be confusing. First, I want to improve that area.

**Comment by jurajsucik** [comment]
OK, I'll start working on it.

**Comment by jurajsucik** [comment]
I submitted this PR https://github.com/shibayan/keyvault-acmebot/pull/89 as a first step.

**Comment by srvrguy** [comment]
Depending on how complex you want to go, it might be worthwhile to use the wiki feature. This will keep the readme document from getting too complex, and allow for better division of content.

**Comment by jurajsucik** [comment]
Agree. At some point we should switch to Wiki. 

Question: it seems to be like enabling AAD authentication is required. if I don't enable authentication I will get "Request failed with status code 401" and DNS zones will not listed out.  Could you confirm?

**Comment by shibayan** [comment]
Yes, you need to enable App Service Authentication. AAD is recommended, though it should work with providers other than AAD.

However, the behavior of the application is difficult to understand (the page can be displayed), so I think we should improve it.

**Comment by jurajsucik** [comment]
ok, clear! But this was not clear from the documentation, so I will update it and submit PR.

**Comment by voyager163** [comment]
Hi Shibayan,

Can i help out in the documentation? I can help out. Do you want to use wiki or readme?

**Comment by shibayan** [comment]
@voyager163 
Improvements to the documentation are always welcome, and once a Pull Request has been created, it will be merge after review.

**Comment by nlem** [comment]
Great work on this.
I have 2 questions and I think the answers should be in the documentation.
Happy to write them up for the readme.
My questions are:

- Best way to delete a certificate that is not needed or incorrect
- How to reinstall or update keyvault-acmebot without deleting existing certificates

Thanks

**Comment by shibayan** [comment]
>Best way to delete a certificate that is not needed or incorrect

Remove the corresponding certificate from the Key Vault

>How to reinstall or update keyvault-acmebot without deleting existing certificates

Don't delete the Key Vault, just rebuild Azure Functions
