### ISSUE TITLE
DNS Made Easy propagation time

### ISSUE THREAD

**Issue by kapral** [shibayan/keyvault-acmebot#778]
Since about a month ago our func started failing with following errors:

```
Exception while executing function: CheckIsReady ACME validation status is invalid. Required retry at first.
LastError = {"type":"urn:ietf:params:acme:error:unauthorized","detail":"Incorrect TXT record \"781M7_QRtliV4Q2WmjG22rsYdfOnd6R1hn_f90uBA4o\" (and 1 more) found at _acme-challenge.<our-domain>","status":403} 
```

When looked at DNS Made Easy logs it's clear that the mentioned record is the one from the previous run. Func logs also indicate that the records were successfully recreated before the failure and the 10 seconds propagation timeout passed.
If I delete the records it fails with an error saying there are no TXT records despite the logs saying they were created.

I ran the function locally and tried increasing the 10 seconds propagation timeout, 15 seconds didn't help but with 30 seconds I managed to renew quite a few of certs.

I'm happy to make a PR with the change, just want your opinion on this stuff. We can just increase the hardcoded value or maybe consider it being configurable?

**Comment by shibayan** [comment]
I am not using DNS Made Easy, so I am not aware of the appropriate propagation timeout. It would be helpful if you could create a pull request.

**Comment by shibayan** [comment]
v4.1.13 Released. Thanks!
