### ISSUE TITLE
Auto-renew

### ISSUE THREAD

**Issue by xidam27** [shibayan/keyvault-acmebot#82]
Hi, how does this app auto renew certs? I can see the new cert added to the keyvault, but not sure where to check the status and how to set the renewal period.

**Comment by shibayan** [comment]
Automatically renews about 30 days before the certificate expires. See Key Vault certificate for renewal results.
There is no way to set the renews interval.

**Comment by rzal** [comment]
That's awesome! Really useful tool for our needs. Thanks! I'll raise another issue regarding the DNS role scope.
