### ISSUE TITLE
Certificates not showing up in Key Vault

### ISSUE THREAD

**Issue by cih997** [shibayan/keyvault-acmebot#96]
Hi. I installed this version https://github.com/shibayan/appservice-acmebot/ and everything worked fine but I needed certs available for Front Door. So I installed https://github.com/shibayan/keyvault-acmebot/ and deleted https://github.com/shibayan/appservice-acmebot/

Everything went fine but now in the keyvault url (YOURAPP.azurewebsites.net/add-certificate) I still see the acmebot form (Add Certificate: Resource Group, App Name, Deployemtn Slot, Domains, Use IP Based SSL). Using this form certificates are generated for the App Service but they don't show up in the Key Vault so cannot use it for Front Door.

Do I still have the acmebot version instead of keyvault? If so - how can I use the keyvault? I've already removed the acmebot version.

Any help much appreciated.

**Comment by shibayan** [comment]
Is appservice-acmebot not properly deleted? If you don't see the keyvault-acmebot form, I don't think it was deployed correctly.

I recommend that you delete all deployed resources and try again.

**Comment by cih997** [comment]
I deleted all resources related to the https://github.com/shibayan/appservice-acmebot/ and now when accessing the keyvault-acmebot add-certificate page I see that form I described above. If that form fields are not coming from keyvault-acmebot, how can I check how it's possible that deleted functions / resources are still running and are available from different resource (in this case it looks like appservice-acmebot form is available from the keyvault-acmebot)?

**Comment by shibayan** [comment]
If the value set in `WEBSITE_RUN_FROM_PACKAGE` of the target Azure Functions correctly points to `https://shibayan.blob.core.windows.net/azure-keyvault-letsencrypt/v3/latest.zip`, the Azure side I think it's a problem so please contact support.

**Comment by jurajsucik** [comment]
@cih997, did you manage to resolve the issue? If not, we can organize a screen sharing session and then we can have a look together.
