### ISSUE TITLE
Certificate renewal succeeded automatically but FrontDoor didn't use new one.

### ISSUE THREAD

**Issue by fujitalon** [shibayan/keyvault-acmebot#97]
I installed keyvault-acmebot about 3 months ago. Everything works fine at this time.
But today, I notice my FrontDoor's certificate is expired.

In keyvault, newer certificate is issued 20 days ago, but FrontDoor is not use it.
I modified FrontDoor manually but I want FrontDoor configuration will be updated automatically when certificate is renewed.

Any help much appreciated.

**Comment by shibayan** [comment]
Look at this issue #60
