### ISSUE TITLE
Call webhook on renew

### ISSUE THREAD

**Issue by withinboredom** [shibayan/keyvault-acmebot#98]
It would be nice if this could call a webhook when a renewal is successful that way certificates can be updated in services that won't automatically use the latest version of a certificate (such as FrontDoor). 

Bonus points if the webhook includes the new version hash of the key to update to and domain to make it easy.

**Comment by shibayan** [comment]
Moved Issue because Key Vault is required for use in Front Door etc.

**Comment by jurajsucik** [comment]
@withinboredom could you describe how the webhook could help to update the cert in service such as Front door? Would you use it with Runbook/Function?

**Comment by shibayan** [comment]
I want to use Key Vault's Event Grid support instead of issuing certificate renewal events from Acmebot. This is architecturally better.

https://docs.microsoft.com/en-us/azure/key-vault/general/event-grid-overview

**Comment by jurajsucik** [comment]
@shibayan could you provide a high-level description of a possible solution based on Event Grid? I can then try it out and document it.

**Comment by shibayan** [comment]
Since Key Grid's Event Grid support is currently in Preview, some events will not be sent. This has been feedback to the development team.

Using Event Grid is more extensible, so even if you implement a webhook on Acmebot, it will be short-lived.

**Comment by withinboredom** [comment]
I didn't notice the preview Event Grid. Thanks for pointing that out @shibayan and @jurajsucik. Feel free to close this out since I also believe this feature to be unnecessary now.
